import type { LessonContent } from '@/lib/course'
import { conversationLine, readingParagraphs } from '@/lib/lesson-text'
import type { VocabularyWord } from '@/lib/course'

/** Apply / Integrate / Unit 5 lessons for Module 01 pathway order. */
export function buildModule1BcLessons(V: VocabularyWord[]): Record<string, LessonContent> {
return {
  '22222222-0000-0000-0000-000000000111': {
    brief: {
      title: "Nationality & origin",
      body: "What this lesson is for: nationality and where you live.\n\n**1. Words to learn first (meanings)**\n- *français* / *française* = French · *anglais* / *anglaise* = English\n- *pays* = country · *ville* = city · *être* = to be · *habiter* = to live\n- *je suis…* = I am… · *j'habite à…* = I live in (city) · *j'habite en…* = I live in (feminine country)\n- *tu es d'où ?* = where are you from?\n\n**2. Nationality** uses *être* + adjective.\n**3. Place** uses *habiter à* (city) / *habiter en* (feminine country).\n**4. Trap:** *C'est Marie* (name) vs *Elle est française* (description).",
      ruleSlugs: ["subject-pronouns", "etre-present", "cest-versus-il-est"],
    },
    reading: readingParagraphs('c1b', [
      "En France, on parle de nationalité et de ville. On dit : Je suis français ou Je suis française. On dit aussi : J'habite à Paris ou J'habite à Lyon. Être sert pour la nationalité. Habiter sert pour le lieu.",
      "Avec un ami : Tu es d'où ? Je suis anglais, mais j'habite en France. C'est Paul identifie. Il est anglais décrit.",
      "Sophie dit : Je m'appelle Sophie. Je suis française. J'habite à Lyon. Thomas dit : Moi, c'est Thomas. Je suis anglais. J'habite à Paris.",
      "Politesse : bonjour, merci, au revoir. Vous avec un inconnu, tu avec un ami. Habiter et être restent deux outils séparés.",
      "En voyage, on demande souvent : Tu es d'où ? Je suis française et j'habite à Marseille. Mon ami Thomas est anglais ; il habite à Paris. La nationalité utilise être : je suis, tu es, il est. La ville utilise habiter : j'habite à Lyon, elle habite en France. On ne dit pas C'est française pour une description — on dit Elle est française. Ces phrases reviennent dans chaque rencontre.",
    ], V),
    conversation: {
      title: "Nationality & origin practice",
      setting: "Nationality & origin practice",
      lines: [
        conversationLine("Ami", "Tu es d'où ?", 'c1b-l0', V),
        conversationLine("Toi", "Je suis français.", 'c1b-l1', V),
        conversationLine("Ami", "Tu habites où ?", 'c1b-l2', V),
        conversationLine("Toi", "J'habite à Lyon.", 'c1b-l3', V),
        conversationLine("Ami", "Et ton amie ?", 'c1b-l4', V),
        conversationLine("Toi", "Elle est française.", 'c1b-l5', V),
        conversationLine("Ami", "Elle habite à Paris ?", 'c1b-l6', V),
        conversationLine("Toi", "Oui, elle habite à Paris.", 'c1b-l7', V),
        conversationLine("Ami", "Tu es étudiant ?", 'c1b-l8', V),
        conversationLine("Toi", "Oui, je suis étudiant.", 'c1b-l9', V),
        conversationLine("Ami", "Enchanté !", 'c1b-l10', V),
        conversationLine("Toi", "Enchanté. À bientôt !", 'c1b-l11', V),
        conversationLine("Ami", "Au revoir !", 'c1b-l12', V),
        conversationLine("Toi", "Merci, au revoir !", 'c1b-l13', V),
      ],
    },
    exercises: [
      {
        id: 'c1b-e1',
        category: "habiter",
        prompt: "“I live in Lyon”:",
        options: ["J'habite à Lyon.", "Je suis à Lyon.", "J'ai Lyon."],
        answer: 0,
        explanation: "habiter à + city",
      },
      {
        id: 'c1b-e2',
        category: "\u00eatre-present",
        prompt: "“I am French” (f.):",
        options: ["Je suis française.", "C'est française.", "J'habite française."],
        answer: 0,
        explanation: "être + nationality",
      },
      {
        id: 'c1b-e3',
        category: "cest-versus-il-est",
        prompt: "Identify by name:",
        options: ["C'est Marie.", "Elle est Marie.", "J'ai Marie."],
        answer: 0,
        explanation: "c'est + name",
      },
      {
        id: 'c1b-e4',
        category: "habiter",
        prompt: "Feminine country:",
        options: ["en", "à", "de"],
        answer: 0,
        explanation: "en France",
      },
      {
        id: 'c1b-e5',
        category: "tu-vous",
        prompt: "Stranger — prefer:",
        options: ["vous", "tu", "il"],
        answer: 0,
        explanation: "vous",
      },
      {
        id: 'c1b-e6',
        category: "\u00eatre-present",
        prompt: "ils/elles + être:",
        options: ["sont", "êtes", "sommes"],
        answer: 0,
        explanation: "sont",
      },
      {
        id: 'c1b-e7',
        category: "habiter",
        prompt: "“She lives in Paris”:",
        options: ["Elle habite à Paris.", "Elle est à Paris.", "Elle a Paris."],
        answer: 0,
        explanation: "habite à",
      },
      {
        id: 'c1b-e8',
        category: "vocab-meaning",
        prompt: "anglais =",
        options: ["English", "French", "city"],
        answer: 0,
        explanation: "English",
      },
      {
        id: 'c1b-e9',
        category: "cest-versus-il-est",
        prompt: "Never:",
        options: ["c'est française", "elle est française", "c'est Marie"],
        answer: 0,
        explanation: "no c'est + adj alone",
      },
      {
        id: 'c1b-e10',
        category: "greetings",
        prompt: "Daytime hello:",
        options: ["bonjour", "salut", "père"],
        answer: 0,
        explanation: "bonjour",
      },
      {
        id: 'c1b-e11',
        category: "\u00eatre-present",
        prompt: "Je ___ français.",
        options: ["suis", "es", "est"],
        answer: 0,
        explanation: "suis",
      },
      {
        id: 'c1b-e12',
        category: "habiter",
        prompt: "j'habite =",
        options: ["I live", "I am", "I have"],
        answer: 0,
        explanation: "I live",
      },
      {
        id: 'c1b-e13',
        category: "subject-pronouns",
        prompt: "elle =",
        options: ["she", "he", "we"],
        answer: 0,
        explanation: "she",
      },
      {
        id: 'c1b-e14',
        category: "\u00eatre-present",
        prompt: "vous êtes =",
        options: ["you are", "we are", "they are"],
        answer: 0,
        explanation: "you are",
      },
      {
        id: 'c1b-e15',
        category: "habiter",
        prompt: "City uses:",
        options: ["à", "en", "dans"],
        answer: 0,
        explanation: "à",
      },
      {
        id: 'c1b-e16',
        category: "identity",
        prompt: "Moi, c'est… =",
        options: ["informal name", "age", "bill"],
        answer: 0,
        explanation: "name",
      },
      {
        id: 'c1b-e17',
        category: "greetings",
        prompt: "à bientôt =",
        options: ["see you soon", "please", "tea"],
        answer: 0,
        explanation: "see you soon",
      },
      {
        id: 'c1b-e18',
        category: "\u00eatre-present",
        prompt: "Nationality verb:",
        options: ["être", "avoir", "prendre"],
        answer: 0,
        explanation: "être",
      },
      {
        id: 'c1b-e19',
        category: "tu-vous",
        prompt: "Friends use:",
        options: ["tu", "vous", "ils"],
        answer: 0,
        explanation: "tu",
      },
      {
        id: 'c1b-e20',
        category: "habiter",
        prompt: "en France because:",
        options: ["feminine country", "city", "number"],
        answer: 0,
        explanation: "country",
      },
      {
        id: 'c1b-e21',
        category: "vocab-meaning",
        prompt: "ville =",
        options: ["city", "brother", "sugar"],
        answer: 0,
        explanation: "city",
      },
      {
        id: 'c1b-e22',
        category: "cest-versus-il-est",
        prompt: "Elle est anglaise =",
        options: ["nationality", "bill", "day"],
        answer: 0,
        explanation: "nationality",
      },
    ],
    wordCount: 250,
  },
  '22222222-0000-0000-0000-000000000112': {
    brief: {
      title: "Checkpoint: three introductions",
      body: "What this lesson is for: mix greetings, names, nationality, and place.\n\n**1. Words to learn first (meanings)**\n- *bonjour* = hello · *je m'appelle* = my name is · *être* = to be · *habiter* = to live\n- *français(e)* = French · *merci* = thank you · *au revoir* = goodbye · *tu* / *vous* = you\n\n**2. Full intro:** greeting + name + nationality + city.\n**3. Traps:** *c'est* names; *il/elle est* nationality; *habiter à* cities.",
      ruleSlugs: ["subject-pronouns", "etre-present", "cest-versus-il-est"],
    },
    reading: readingParagraphs('c1c', [
      "Première présentation : Bonjour ! Je m'appelle Marc. Je suis français. J'habite à Paris. Enchanté ! Merci et au revoir à la fin.",
      "Deuxième : Salut ! Moi, c'est Sophie. Je suis française. J'habite à Lyon. Comment ça va ? Ça va bien, merci.",
      "Troisième : Bonjour ! Comment vous appelez-vous ? Je m'appelle Thomas. Je suis anglais. J'habite en France, à Paris. Au revoir !",
      "Tu avec un ami, vous avec un professeur. C'est Marc pour le nom. Il est anglais pour la nationalité. J'habite à Paris pour la ville.",
      "Première rencontre : Bonjour, je m'appelle Sophie. Je suis française. Deuxième : Enchanté, moi c'est Marc. Je suis étudiant. Troisième : Comment vous appelez-vous ? Je m'appelle Thomas. Je suis anglais et j'habite à Paris. Chaque version présente un nom, une nationalité et parfois une ville. Répétez les trois modèles à voix haute avant le dialogue.",
    ], V),
    conversation: {
      title: "Checkpoint: three introductions practice",
      setting: "Checkpoint: three introductions practice",
      lines: [
        conversationLine("Professeur", "Bonjour ! Comment vous appelez-vous ?", 'c1c-l0', V),
        conversationLine("\u00c9l\u00e8ve", "Je m'appelle Lea.", 'c1c-l1', V),
        conversationLine("Professeur", "Vous êtes française ?", 'c1c-l2', V),
        conversationLine("\u00c9l\u00e8ve", "Oui, je suis française.", 'c1c-l3', V),
        conversationLine("Professeur", "Vous habitez où ?", 'c1c-l4', V),
        conversationLine("\u00c9l\u00e8ve", "J'habite à Lyon.", 'c1c-l5', V),
        conversationLine("Ami", "Salut ! Tu es d'où ?", 'c1c-l6', V),
        conversationLine("Toi", "Je suis français. J'habite à Paris.", 'c1c-l7', V),
        conversationLine("Ami", "Moi aussi !", 'c1c-l8', V),
        conversationLine("Toi", "À bientôt !", 'c1c-l9', V),
        conversationLine("Ami", "Au revoir !", 'c1c-l10', V),
        conversationLine("Toi", "Merci !", 'c1c-l11', V),
        conversationLine("Serveur", "Bonjour.", 'c1c-l12', V),
        conversationLine("Client", "Bonjour. Au revoir !", 'c1c-l13', V),
      ],
    },
    exercises: [
      {
        id: 'c1c-e1',
        category: "identity",
        prompt: "Informal intro often uses:",
        options: ["Salut / Moi, c'est…", "L'addition", "Du sucre"],
        answer: 0,
        explanation: "informal",
      },
      {
        id: 'c1c-e2',
        category: "\u00eatre-present",
        prompt: "Je suis anglaise —",
        options: ["feminine", "always masculine", "plural only"],
        answer: 0,
        explanation: "feminine",
      },
      {
        id: 'c1c-e3',
        category: "habiter",
        prompt: "I live in Paris:",
        options: ["J'habite à Paris.", "Je suis Paris.", "J'ai Paris."],
        answer: 0,
        explanation: "habite à",
      },
      {
        id: 'c1c-e4',
        category: "tu-vous",
        prompt: "Teacher usually:",
        options: ["vous", "tu", "on"],
        answer: 0,
        explanation: "vous",
      },
      {
        id: 'c1c-e5',
        category: "cest-versus-il-est",
        prompt: "C'est Thomas",
        options: ["identifies", "age", "bill"],
        answer: 0,
        explanation: "name",
      },
      {
        id: 'c1c-e6',
        category: "greetings",
        prompt: "Daytime:",
        options: ["bonjour", "bonsoir", "hier"],
        answer: 0,
        explanation: "bonjour",
      },
      {
        id: 'c1c-e7',
        category: "\u00eatre-present",
        prompt: "nous sommes =",
        options: ["we are", "you are", "they are"],
        answer: 0,
        explanation: "we are",
      },
      {
        id: 'c1c-e8',
        category: "habiter",
        prompt: "en France:",
        options: ["en", "à", "de"],
        answer: 0,
        explanation: "en",
      },
      {
        id: 'c1c-e9',
        category: "subject-pronouns",
        prompt: "nous =",
        options: ["we", "I", "they"],
        answer: 0,
        explanation: "we",
      },
      {
        id: 'c1c-e10',
        category: "greetings",
        prompt: "merci =",
        options: ["thank you", "please", "hello"],
        answer: 0,
        explanation: "thank you",
      },
      {
        id: 'c1c-e11',
        category: "identity",
        prompt: "Je m'appelle",
        options: ["my name is", "I live", "I pay"],
        answer: 0,
        explanation: "name",
      },
      {
        id: 'c1c-e12',
        category: "\u00eatre-present",
        prompt: "Tu ___ français.",
        options: ["es", "suis", "sommes"],
        answer: 0,
        explanation: "es",
      },
      {
        id: 'c1c-e13',
        category: "tu-vous",
        prompt: "Two friends:",
        options: ["tu", "vous", "madame"],
        answer: 0,
        explanation: "tu",
      },
      {
        id: 'c1c-e14',
        category: "habiter",
        prompt: "habiter =",
        options: ["to live", "to be", "to have"],
        answer: 0,
        explanation: "to live",
      },
      {
        id: 'c1c-e15',
        category: "cest-versus-il-est",
        prompt: "Elle est française",
        options: ["description", "name only", "tea"],
        answer: 0,
        explanation: "description",
      },
      {
        id: 'c1c-e16',
        category: "greetings",
        prompt: "au revoir =",
        options: ["goodbye", "please", "today"],
        answer: 0,
        explanation: "goodbye",
      },
      {
        id: 'c1c-e17',
        category: "vocab-meaning",
        prompt: "étudiant =",
        options: ["student", "city", "brother"],
        answer: 0,
        explanation: "student",
      },
      {
        id: 'c1c-e18',
        category: "\u00eatre-present",
        prompt: "ils sont =",
        options: ["they are", "we are", "I am"],
        answer: 0,
        explanation: "they are",
      },
      {
        id: 'c1c-e19',
        category: "identity",
        prompt: "Enchanté =",
        options: ["pleased to meet you", "bill", "water"],
        answer: 0,
        explanation: "pleased",
      },
      {
        id: 'c1c-e20',
        category: "habiter",
        prompt: "à Lyon =",
        options: ["city", "country", "verb"],
        answer: 0,
        explanation: "city",
      },
      {
        id: 'c1c-e21',
        category: "subject-pronouns",
        prompt: "je =",
        options: ["I", "you", "he"],
        answer: 0,
        explanation: "I",
      },
      {
        id: 'c1c-e22',
        category: "greetings",
        prompt: "à bientôt =",
        options: ["see you soon", "father", "tea"],
        answer: 0,
        explanation: "soon",
      },
    ],
    wordCount: 234,
  },
  '22222222-0000-0000-0000-000000000121': {
    brief: {
      title: "Planning the week",
      body: "What this lesson is for: plan days with clear meanings first.\n\n**1. Words to learn first (meanings)**\n- *lundi…dimanche* = Monday…Sunday · *aujourd'hui* = today · *demain* = tomorrow · *hier* = yesterday\n- *semaine* = week · *avoir* = to have · *ans* = years (age) · *anniversaire* = birthday\n- *on se voit…* = see you on… · *quel âge as-tu ?* = how old are you?\n\n**2. Age:** *j'ai … ans* (never *je suis … ans*).\n**3. Days:** lowercase; *On se voit samedi ?*",
      ruleSlugs: ["numbers-and-age"],
    },
    reading: readingParagraphs('c2b', [
      "Cette semaine, le calendrier est important. Aujourd'hui, c'est lundi. Demain, c'est mardi. Hier, c'était dimanche. Les jours ne prennent pas de majuscule en français : lundi, mardi, mercredi…",
      "Pour l'âge, on utilise avoir : J'ai vingt ans. On ne dit pas Je suis vingt ans. Question : Quel âge as-tu ? Réponse : J'ai vingt-cinq ans.",
      "Pour un rendez-vous : On se voit vendredi ? Mon anniversaire est samedi. La semaine prochaine, on se voit lundi.",
      "Regardez le calendrier : semaine, mois, année. Les nombres servent partout — âge, dates, prix plus tard. Apprenez 1–20 solidement.",
      "Lundi, mardi, mercredi : la semaine commence. On dit : Quel jour sommes-nous ? Aujourd'hui, c'est mercredi. Demain, c'est jeudi. On se voit vendredi ? Oui, à quinze heures. La semaine prochaine, on se voit lundi. Les jours de la semaine aident à fixer un rendez-vous.",
    ], V),
    conversation: {
      title: "Planning the week practice",
      setting: "Planning the week practice",
      lines: [
        conversationLine("Ami", "Quel âge as-tu ?", 'c2b-l0', V),
        conversationLine("Toi", "J'ai vingt ans.", 'c2b-l1', V),
        conversationLine("Ami", "On se voit vendredi ?", 'c2b-l2', V),
        conversationLine("Toi", "Oui, vendredi.", 'c2b-l3', V),
        conversationLine("Ami", "Et demain ?", 'c2b-l4', V),
        conversationLine("Toi", "Demain, c'est jeudi.", 'c2b-l5', V),
        conversationLine("Ami", "Ton anniversaire est quand ?", 'c2b-l6', V),
        conversationLine("Toi", "Samedi.", 'c2b-l7', V),
        conversationLine("Ami", "Super !", 'c2b-l8', V),
        conversationLine("Toi", "Aujourd'hui je travaille.", 'c2b-l9', V),
        conversationLine("Ami", "Et hier ?", 'c2b-l10', V),
        conversationLine("Toi", "Hier, c'était calme.", 'c2b-l11', V),
        conversationLine("Ami", "À bientôt !", 'c2b-l12', V),
        conversationLine("Toi", "À bientôt !", 'c2b-l13', V),
      ],
    },
    exercises: [
      {
        id: 'c2b-e1',
        category: "numbers-and-age",
        prompt: "Age uses:",
        options: ["avoir", "être", "prendre"],
        answer: 0,
        explanation: "avoir",
      },
      {
        id: 'c2b-e2',
        category: "days",
        prompt: "Friday =",
        options: ["vendredi", "lundi", "dimanche"],
        answer: 0,
        explanation: "vendredi",
      },
      {
        id: 'c2b-e3',
        category: "numbers-and-age",
        prompt: "J'ai vingt ans =",
        options: ["I am 20", "I have twenty brothers", "Today is Monday"],
        answer: 0,
        explanation: "age",
      },
      {
        id: 'c2b-e4',
        category: "days",
        prompt: "aujourd'hui =",
        options: ["today", "tomorrow", "yesterday"],
        answer: 0,
        explanation: "today",
      },
      {
        id: 'c2b-e5',
        category: "days",
        prompt: "demain =",
        options: ["tomorrow", "today", "week"],
        answer: 0,
        explanation: "tomorrow",
      },
      {
        id: 'c2b-e6',
        category: "days",
        prompt: "hier =",
        options: ["yesterday", "tomorrow", "month"],
        answer: 0,
        explanation: "yesterday",
      },
      {
        id: 'c2b-e7',
        category: "numbers-and-age",
        prompt: "Ask age informal:",
        options: ["Quel âge as-tu ?", "Tu es vingt ?", "Où habites-tu ?"],
        answer: 0,
        explanation: "quel âge",
      },
      {
        id: 'c2b-e8',
        category: "days",
        prompt: "On se voit samedi ?",
        options: ["See you Saturday?", "I am Saturday", "Pay Saturday"],
        answer: 0,
        explanation: "meet",
      },
      {
        id: 'c2b-e9',
        category: "numbers-and-age",
        prompt: "Never:",
        options: ["Je suis vingt ans", "J'ai vingt ans", "Quel âge as-tu ?"],
        answer: 0,
        explanation: "no être for age",
      },
      {
        id: 'c2b-e10',
        category: "days",
        prompt: "Days are:",
        options: ["not capitalized", "always Capitals", "English only"],
        answer: 0,
        explanation: "lowercase",
      },
      {
        id: 'c2b-e11',
        category: "numbers-and-age",
        prompt: "dix =",
        options: ["10", "2", "20"],
        answer: 0,
        explanation: "10",
      },
      {
        id: 'c2b-e12',
        category: "numbers-and-age",
        prompt: "vingt =",
        options: ["20", "12", "2"],
        answer: 0,
        explanation: "20",
      },
      {
        id: 'c2b-e13',
        category: "days",
        prompt: "semaine =",
        options: ["week", "day", "year"],
        answer: 0,
        explanation: "week",
      },
      {
        id: 'c2b-e14',
        category: "days",
        prompt: "lundi =",
        options: ["Monday", "Sunday", "Friday"],
        answer: 0,
        explanation: "Monday",
      },
      {
        id: 'c2b-e15',
        category: "numbers-and-age",
        prompt: "anniversaire =",
        options: ["birthday", "bill", "tea"],
        answer: 0,
        explanation: "birthday",
      },
      {
        id: 'c2b-e16',
        category: "days",
        prompt: "dimanche =",
        options: ["Sunday", "Monday", "Tuesday"],
        answer: 0,
        explanation: "Sunday",
      },
      {
        id: 'c2b-e17',
        category: "numbers-and-age",
        prompt: "tu as =",
        options: ["you have", "you are", "you live"],
        answer: 0,
        explanation: "avoir",
      },
      {
        id: 'c2b-e18',
        category: "days",
        prompt: "mercredi =",
        options: ["Wednesday", "Thursday", "Saturday"],
        answer: 0,
        explanation: "Wednesday",
      },
      {
        id: 'c2b-e19',
        category: "numbers-and-age",
        prompt: "quinze =",
        options: ["15", "5", "50"],
        answer: 0,
        explanation: "15",
      },
      {
        id: 'c2b-e20',
        category: "days",
        prompt: "la semaine prochaine =",
        options: ["next week", "yesterday", "father"],
        answer: 0,
        explanation: "next week",
      },
      {
        id: 'c2b-e21',
        category: "numbers-and-age",
        prompt: "Elle a trente ans.",
        options: ["She is 30", "She has 30 brothers", "She lives 30"],
        answer: 0,
        explanation: "age",
      },
      {
        id: 'c2b-e22',
        category: "days",
        prompt: "jeudi =",
        options: ["Thursday", "Tuesday", "Friday"],
        answer: 0,
        explanation: "Thursday",
      },
    ],
    wordCount: 239,
  },
  '22222222-0000-0000-0000-000000000122': {
    brief: {
      title: "Checkpoint: a week agenda",
      body: "What this lesson is for: mix numbers, days, and age in one agenda.\n\n**1. Words to learn first (meanings)**\nReview days, *aujourd'hui/demain/hier*, *avoir … ans*, *anniversaire*, *semaine*.\n\n**2. Build:** age sentence + two day plans + one birthday line.",
      ruleSlugs: ["numbers-and-age"],
    },
    reading: readingParagraphs('c2c', [
      "Agenda : Lundi — cours. Mardi — café avec un ami. Mercredi — repos. Jeudi — travail. Vendredi — cinéma. Samedi — anniversaire. Dimanche — famille.",
      "Aujourd'hui, c'est mercredi. Demain, c'est jeudi. Hier, c'était mardi. J'ai vingt-deux ans. Mon anniversaire est samedi.",
      "On se voit vendredi ? Oui. Quel âge as-tu ? J'ai vingt-deux ans. La semaine prochaine, on se voit lundi.",
      "Les nombres 1–20 reviennent : un, deux, trois… vingt. Avoir + nombre + ans pour l'âge. Pas être.",
      "Le calendrier mélange jours et nombres. Quel âge as-tu ? J'ai vingt ans. Mon anniversaire est en mars. On compte : un, deux, trois… jusqu'à vingt. Avoir + nombre + ans pour l'âge — jamais je suis vingt ans. Combinez jour et date : samedi, le huit mars.",
    ], V),
    conversation: {
      title: "Checkpoint: a week agenda practice",
      setting: "Checkpoint: a week agenda practice",
      lines: [
        conversationLine("Ami", "Aujourd'hui, c'est quel jour ?", 'c2c-l0', V),
        conversationLine("Toi", "C'est mercredi.", 'c2c-l1', V),
        conversationLine("Ami", "On se voit demain ?", 'c2c-l2', V),
        conversationLine("Toi", "Oui, demain.", 'c2c-l3', V),
        conversationLine("Ami", "Quel âge as-tu ?", 'c2c-l4', V),
        conversationLine("Toi", "J'ai vingt-deux ans.", 'c2c-l5', V),
        conversationLine("Ami", "Ton anniversaire ?", 'c2c-l6', V),
        conversationLine("Toi", "Samedi.", 'c2c-l7', V),
        conversationLine("Ami", "Super.", 'c2c-l8', V),
        conversationLine("Toi", "Et toi ?", 'c2c-l9', V),
        conversationLine("Ami", "J'ai vingt-trois ans.", 'c2c-l10', V),
        conversationLine("Toi", "Cool !", 'c2c-l11', V),
        conversationLine("Ami", "À vendredi !", 'c2c-l12', V),
        conversationLine("Toi", "À vendredi !", 'c2c-l13', V),
      ],
    },
    exercises: [
      {
        id: 'c2c-e1',
        category: "days",
        prompt: "Agenda Saturday often:",
        options: ["anniversaire / outing", "être only", "addition"],
        answer: 0,
        explanation: "weekend",
      },
      {
        id: 'c2c-e2',
        category: "numbers-and-age",
        prompt: "J'ai vingt-deux ans",
        options: ["I am 22", "I live 22", "I order 22"],
        answer: 0,
        explanation: "age",
      },
      {
        id: 'c2c-e3',
        category: "days",
        prompt: "demain after mercredi:",
        options: ["jeudi", "lundi", "dimanche"],
        answer: 0,
        explanation: "jeudi",
      },
      {
        id: 'c2c-e4',
        category: "numbers-and-age",
        prompt: "Age verb:",
        options: ["avoir", "être", "aimer"],
        answer: 0,
        explanation: "avoir",
      },
      {
        id: 'c2c-e5',
        category: "days",
        prompt: "On se voit vendredi",
        options: ["meet Friday", "pay Friday", "be Friday"],
        answer: 0,
        explanation: "meet",
      },
      {
        id: 'c2c-e6',
        category: "days",
        prompt: "hier =",
        options: ["yesterday", "tomorrow", "week"],
        answer: 0,
        explanation: "yesterday",
      },
      {
        id: 'c2c-e7',
        category: "numbers-and-age",
        prompt: "trois =",
        options: ["3", "13", "30"],
        answer: 0,
        explanation: "3",
      },
      {
        id: 'c2c-e8',
        category: "days",
        prompt: "dimanche =",
        options: ["Sunday", "Monday", "Friday"],
        answer: 0,
        explanation: "Sunday",
      },
      {
        id: 'c2c-e9',
        category: "numbers-and-age",
        prompt: "Ask formal age:",
        options: ["Quel âge avez-vous ?", "Tu es âge ?", "Où ?"],
        answer: 0,
        explanation: "avez-vous",
      },
      {
        id: 'c2c-e10',
        category: "days",
        prompt: "semaine =",
        options: ["week", "sugar", "sister"],
        answer: 0,
        explanation: "week",
      },
      {
        id: 'c2c-e11',
        category: "numbers-and-age",
        prompt: "Never Je suis X ans",
        options: ["true", "false", "maybe"],
        answer: 0,
        explanation: "true that never",
      },
      {
        id: 'c2c-e12',
        category: "days",
        prompt: "lundi =",
        options: ["Monday", "Friday", "Sunday"],
        answer: 0,
        explanation: "Monday",
      },
      {
        id: 'c2c-e13',
        category: "numbers-and-age",
        prompt: "douze =",
        options: ["12", "2", "20"],
        answer: 0,
        explanation: "12",
      },
      {
        id: 'c2c-e14',
        category: "days",
        prompt: "aujourd'hui =",
        options: ["today", "yesterday", "month"],
        answer: 0,
        explanation: "today",
      },
      {
        id: 'c2c-e15',
        category: "numbers-and-age",
        prompt: "anniversaire =",
        options: ["birthday", "bread", "tea"],
        answer: 0,
        explanation: "birthday",
      },
      {
        id: 'c2c-e16',
        category: "days",
        prompt: "samedi =",
        options: ["Saturday", "Sunday", "Monday"],
        answer: 0,
        explanation: "Saturday",
      },
      {
        id: 'c2c-e17',
        category: "numbers-and-age",
        prompt: "cinq =",
        options: ["5", "15", "50"],
        answer: 0,
        explanation: "5",
      },
      {
        id: 'c2c-e18',
        category: "days",
        prompt: "jeudi =",
        options: ["Thursday", "Tuesday", "Wednesday"],
        answer: 0,
        explanation: "Thursday",
      },
      {
        id: 'c2c-e19',
        category: "numbers-and-age",
        prompt: "tu as =",
        options: ["you have", "you are", "you go"],
        answer: 0,
        explanation: "have",
      },
      {
        id: 'c2c-e20',
        category: "days",
        prompt: "mardi =",
        options: ["Tuesday", "Thursday", "Sunday"],
        answer: 0,
        explanation: "Tuesday",
      },
      {
        id: 'c2c-e21',
        category: "numbers-and-age",
        prompt: "seize =",
        options: ["16", "6", "60"],
        answer: 0,
        explanation: "16",
      },
      {
        id: 'c2c-e22',
        category: "days",
        prompt: "vendredi =",
        options: ["Friday", "Wednesday", "Monday"],
        answer: 0,
        explanation: "Friday",
      },
    ],
    wordCount: 223,
  },
  '22222222-0000-0000-0000-000000000131': {
    brief: {
      title: "Bill & politeness",
      body: "What this lesson is for: ask for the bill and stay polite.\n\n**1. Words to learn first (meanings)**\n- *addition* = bill · *payer* = to pay · *s'il vous plaît* = please · *merci* = thank you · *de rien* = you are welcome\n- *euro* = euro · *serveur/serveuse* = waiter/waitress · *prendre* = to have (food/drink) · *vouloir* = to want\n\n**2. Chunks:** *L'addition, s'il vous plaît.* · *Je voudrais…* · *Ça fait … euros.*\n**3. Register:** *vous* with staff.",
      ruleSlugs: ["articles-partitives", "er-present", "silent-final-consonants"],
    },
    reading: readingParagraphs('c3b', [
      "Au café, la politesse compte. On dit bonjour en entrant. On commande : Je prends un café, s'il vous plaît. Ou : Je voudrais un thé et de l'eau.",
      "Pour payer : L'addition, s'il vous plaît. Le serveur dit : Ça fait sept euros. On répond merci. Il peut dire de rien.",
      "Les articles : un café (one cup), du thé (some tea), de l'eau (some water). Comptez les objets avec un/une. Pour une quantité : du / de la / de l'.",
      "Silent letters : in vous voulez, final sound often drops. Spelling still keeps the letters. Use vous with staff — not salut.",
      "Au café, d'abord bonjour. Ensuite : Un café, s'il vous plaît. Et pour vous ? Un thé, merci. L'addition, s'il vous plaît. Combien ça coûte ? Voici dix euros. Gardez la monnaie. Au revoir ! Vouvoyer le serveur reste la norme.",
    ], V),
    conversation: {
      title: "Bill & politeness practice",
      setting: "Bill & politeness practice",
      lines: [
        conversationLine("Serveur", "Vous désirez ?", 'c3b-l0', V),
        conversationLine("Client", "Je voudrais un café, s'il vous plaît.", 'c3b-l1', V),
        conversationLine("Serveur", "Et avec ceci ?", 'c3b-l2', V),
        conversationLine("Client", "De l'eau, s'il vous plaît.", 'c3b-l3', V),
        conversationLine("Client", "L'addition, s'il vous plaît.", 'c3b-l4', V),
        conversationLine("Serveur", "Ça fait sept euros.", 'c3b-l5', V),
        conversationLine("Client", "Merci.", 'c3b-l6', V),
        conversationLine("Serveur", "De rien.", 'c3b-l7', V),
        conversationLine("Client", "Au revoir.", 'c3b-l8', V),
        conversationLine("Serveur", "Au revoir.", 'c3b-l9', V),
        conversationLine("Client", "Bonjour !", 'c3b-l10', V),
        conversationLine("Serveur", "Bonjour.", 'c3b-l11', V),
        conversationLine("Client", "Je prends un thé.", 'c3b-l12', V),
        conversationLine("Serveur", "Très bien.", 'c3b-l13', V),
      ],
    },
    exercises: [
      {
        id: 'c3b-e1',
        category: "politeness",
        prompt: "Ask for the bill:",
        options: ["L'addition, s'il vous plaît.", "Salut addition", "Je suis addition"],
        answer: 0,
        explanation: "addition",
      },
      {
        id: 'c3b-e2',
        category: "articles-partitives",
        prompt: "some water:",
        options: ["de l'eau", "un eau", "la eau"],
        answer: 0,
        explanation: "de l'eau",
      },
      {
        id: 'c3b-e3',
        category: "ordering",
        prompt: "Polite want:",
        options: ["je voudrais", "je suis", "j'habite"],
        answer: 0,
        explanation: "voudrais",
      },
      {
        id: 'c3b-e4',
        category: "politeness",
        prompt: "merci =",
        options: ["thank you", "bill", "tea"],
        answer: 0,
        explanation: "thanks",
      },
      {
        id: 'c3b-e5',
        category: "politeness",
        prompt: "de rien =",
        options: ["you are welcome", "goodbye", "sugar"],
        answer: 0,
        explanation: "welcome",
      },
      {
        id: 'c3b-e6',
        category: "caf\u00e9-vocab",
        prompt: "addition =",
        options: ["bill", "brother", "Monday"],
        answer: 0,
        explanation: "bill",
      },
      {
        id: 'c3b-e7',
        category: "articles-partitives",
        prompt: "un croissant =",
        options: ["one croissant", "some croissant", "the water"],
        answer: 0,
        explanation: "countable",
      },
      {
        id: 'c3b-e8',
        category: "payer",
        prompt: "payer =",
        options: ["to pay", "to live", "to be"],
        answer: 0,
        explanation: "pay",
      },
      {
        id: 'c3b-e9',
        category: "tu-vous",
        prompt: "Staff get:",
        options: ["vous", "tu", "ils"],
        answer: 0,
        explanation: "vous",
      },
      {
        id: 'c3b-e10',
        category: "ordering",
        prompt: "Je prends un café",
        options: ["I'll have a coffee", "I am coffee", "I live coffee"],
        answer: 0,
        explanation: "order",
      },
      {
        id: 'c3b-e11',
        category: "silent-final-consonants",
        prompt: "Final letters often:",
        options: ["silent in speech", "always shouted", "English"],
        answer: 0,
        explanation: "silent",
      },
      {
        id: 'c3b-e12',
        category: "articles-partitives",
        prompt: "du thé =",
        options: ["some tea", "one tea cup forced", "father"],
        answer: 0,
        explanation: "partitive",
      },
      {
        id: 'c3b-e13',
        category: "caf\u00e9-vocab",
        prompt: "serveur =",
        options: ["waiter", "sister", "week"],
        answer: 0,
        explanation: "waiter",
      },
      {
        id: 'c3b-e14',
        category: "politeness",
        prompt: "s'il vous plaît =",
        options: ["please", "hello", "today"],
        answer: 0,
        explanation: "please",
      },
      {
        id: 'c3b-e15',
        category: "ordering",
        prompt: "Vous désirez ?",
        options: ["What would you like?", "How old?", "Where live?"],
        answer: 0,
        explanation: "order ask",
      },
      {
        id: 'c3b-e16',
        category: "caf\u00e9-vocab",
        prompt: "euro =",
        options: ["euro", "water", "brother"],
        answer: 0,
        explanation: "euro",
      },
      {
        id: 'c3b-e17',
        category: "prendre",
        prompt: "je prends =",
        options: ["I take/have", "I am", "I have age"],
        answer: 0,
        explanation: "prendre",
      },
      {
        id: 'c3b-e18',
        category: "articles-partitives",
        prompt: "de la =",
        options: ["some (f.)", "one (m.)", "they"],
        answer: 0,
        explanation: "partitive f",
      },
      {
        id: 'c3b-e19',
        category: "greetings",
        prompt: "Enter café with:",
        options: ["bonjour", "addition", "hier"],
        answer: 0,
        explanation: "bonjour",
      },
      {
        id: 'c3b-e20',
        category: "payer",
        prompt: "Ça fait sept euros",
        options: ["That comes to 7€", "I am 7", "Live 7"],
        answer: 0,
        explanation: "price",
      },
      {
        id: 'c3b-e21',
        category: "caf\u00e9-vocab",
        prompt: "thé =",
        options: ["tea", "tea bag only English", "father"],
        answer: 0,
        explanation: "tea",
      },
      {
        id: 'c3b-e22',
        category: "politeness",
        prompt: "End with:",
        options: ["merci / au revoir", "tu es", "j'ai ans"],
        answer: 0,
        explanation: "thanks bye",
      },
    ],
    wordCount: 248,
  },
  '22222222-0000-0000-0000-000000000132': {
    brief: {
      title: "Checkpoint: terrace",
      body: "What this lesson is for: full café scene on the terrace.\n\n**1. Words to learn first (meanings)**\n- *terrasse* = outdoor seating · *café/thé/eau/croissant* · *addition* · *s'il vous plaît* · *prendre/vouloir/payer*\n\n**2. Order + pay + polite close.**",
      ruleSlugs: ["articles-partitives", "er-present", "silent-final-consonants"],
    },
    reading: readingParagraphs('c3c', [
      "Ils s'installent à la terrasse. Le serveur demande : Vous désirez ? Elle prend un thé. Il prend un café et un croissant. Ils veulent aussi de l'eau.",
      "S'il vous plaît termine la commande. Plus tard : L'addition, s'il vous plaît. Ça fait douze euros. Merci — de rien — au revoir.",
      "Articles : un café, un croissant, du sucre, de l'eau. Ne dites pas je suis un café.",
      "La terrasse est dehors. On dit bonjour en arrivant. On garde vous avec le personnel. Les verbes prendre, vouloir et payer organisent toute la scène.",
      "Sur la terrasse, il fait beau. Je prends un café et un croissant. Tu veux de l'eau ? Oui, de l'eau, merci. C'est combien ? Sept euros. Je paie. Les articles un, du, de l'organisent la commande : un café, du thé, de l'eau.",
    ], V),
    conversation: {
      title: "Checkpoint: terrace practice",
      setting: "Checkpoint: terrace practice",
      lines: [
        conversationLine("Serveur", "Vous désirez ?", 'c3c-l0', V),
        conversationLine("Cliente", "Un thé, s'il vous plaît.", 'c3c-l1', V),
        conversationLine("Client", "Un café et un croissant.", 'c3c-l2', V),
        conversationLine("Serveur", "Et de l'eau ?", 'c3c-l3', V),
        conversationLine("Cliente", "Oui, de l'eau.", 'c3c-l4', V),
        conversationLine("Client", "L'addition, s'il vous plaît.", 'c3c-l5', V),
        conversationLine("Serveur", "Douze euros.", 'c3c-l6', V),
        conversationLine("Client", "Merci.", 'c3c-l7', V),
        conversationLine("Serveur", "De rien.", 'c3c-l8', V),
        conversationLine("Cliente", "Au revoir.", 'c3c-l9', V),
        conversationLine("Serveur", "Au revoir.", 'c3c-l10', V),
        conversationLine("Cliente", "Bonne journée.", 'c3c-l11', V),
        conversationLine("Client", "Bonjour !", 'c3c-l12', V),
        conversationLine("Serveur", "Bonjour.", 'c3c-l13', V),
      ],
    },
    exercises: [
      {
        id: 'c3c-e1',
        category: "caf\u00e9-vocab",
        prompt: "terrasse =",
        options: ["patio seating", "father", "Monday"],
        answer: 0,
        explanation: "terrace",
      },
      {
        id: 'c3c-e2',
        category: "ordering",
        prompt: "Order tea:",
        options: ["un thé", "du père", "la semaine"],
        answer: 0,
        explanation: "thé",
      },
      {
        id: 'c3c-e3',
        category: "articles-partitives",
        prompt: "de l'eau",
        options: ["some water", "one father", "Tuesday"],
        answer: 0,
        explanation: "water",
      },
      {
        id: 'c3c-e4',
        category: "politeness",
        prompt: "Bill line:",
        options: ["L'addition, s'il vous plaît.", "Je suis addition", "Tu addition"],
        answer: 0,
        explanation: "bill",
      },
      {
        id: 'c3c-e5',
        category: "prendre",
        prompt: "Ils prennent",
        options: ["they have/order", "they are", "they live"],
        answer: 0,
        explanation: "prendre",
      },
      {
        id: 'c3c-e6',
        category: "articles-partitives",
        prompt: "un croissant",
        options: ["countable", "partitive mass", "day"],
        answer: 0,
        explanation: "un",
      },
      {
        id: 'c3c-e7',
        category: "politeness",
        prompt: "merci",
        options: ["thank you", "bill", "tea"],
        answer: 0,
        explanation: "thanks",
      },
      {
        id: 'c3c-e8',
        category: "caf\u00e9-vocab",
        prompt: "croissant =",
        options: ["croissant", "sister", "week"],
        answer: 0,
        explanation: "croissant",
      },
      {
        id: 'c3c-e9',
        category: "tu-vous",
        prompt: "Waiter:",
        options: ["vous", "tu", "ils"],
        answer: 0,
        explanation: "vous",
      },
      {
        id: 'c3c-e10',
        category: "payer",
        prompt: "to pay:",
        options: ["payer", "habiter", "être"],
        answer: 0,
        explanation: "payer",
      },
      {
        id: 'c3c-e11',
        category: "ordering",
        prompt: "je voudrais",
        options: ["I would like", "I am", "I live"],
        answer: 0,
        explanation: "voudrais",
      },
      {
        id: 'c3c-e12',
        category: "articles-partitives",
        prompt: "du sucre",
        options: ["some sugar", "one sugar forced wrong", "age"],
        answer: 0,
        explanation: "du",
      },
      {
        id: 'c3c-e13',
        category: "greetings",
        prompt: "bonjour",
        options: ["hello", "bill", "tea"],
        answer: 0,
        explanation: "hello",
      },
      {
        id: 'c3c-e14',
        category: "silent-final-consonants",
        prompt: "ils prennent ending",
        options: ["often silent", "always loud", "English"],
        answer: 0,
        explanation: "silent",
      },
      {
        id: 'c3c-e15',
        category: "caf\u00e9-vocab",
        prompt: "boisson =",
        options: ["drink", "brother", "Friday"],
        answer: 0,
        explanation: "drink",
      },
      {
        id: 'c3c-e16',
        category: "politeness",
        prompt: "de rien",
        options: ["you are welcome", "goodbye", "city"],
        answer: 0,
        explanation: "welcome",
      },
      {
        id: 'c3c-e17',
        category: "ordering",
        prompt: "Vous désirez",
        options: ["What would you like?", "How old?", "Where?"],
        answer: 0,
        explanation: "desire",
      },
      {
        id: 'c3c-e18',
        category: "articles-partitives",
        prompt: "une",
        options: ["feminine a/one", "masculine a", "they"],
        answer: 0,
        explanation: "une",
      },
      {
        id: 'c3c-e19',
        category: "caf\u00e9-vocab",
        prompt: "menu =",
        options: ["menu", "mother", "Monday"],
        answer: 0,
        explanation: "menu",
      },
      {
        id: 'c3c-e20',
        category: "prendre",
        prompt: "je prends",
        options: ["I'll have", "I am age", "I live"],
        answer: 0,
        explanation: "prends",
      },
      {
        id: 'c3c-e21',
        category: "politeness",
        prompt: "s'il vous plaît",
        options: ["please", "hello", "father"],
        answer: 0,
        explanation: "please",
      },
      {
        id: 'c3c-e22',
        category: "greetings",
        prompt: "au revoir",
        options: ["goodbye", "tea", "age"],
        answer: 0,
        explanation: "bye",
      },
    ],
    wordCount: 237,
  },
  '22222222-0000-0000-0000-000000000141': {
    brief: {
      title: "Descriptions with être",
      body: "What this lesson is for: describe family after you know the words.\n\n**1. Words to learn first (meanings)**\n- *père*=father · *mère*=mother · *frère*=brother · *sœur*=sister · *parents*=parents\n- *grand/grande*=tall · *jeune*=young · *être*=to be · *mon/ma/mes*=my\n\n**2. Pattern:** *Mon père est grand.* Possessive + noun + être + adjective.\n**3. Agreement:** *française*, *grande* for feminine.",
      ruleSlugs: ["possessive-adjectives", "etre-present"],
    },
    reading: readingParagraphs('c4b', [
      "D'abord les sens : père = father, mère = mother, frère = brother, sœur = sister. Puis la grammaire : Mon père est grand. Ma mère est jeune. Mes parents sont français.",
      "Avoir pour posséder : J'ai un frère. Être pour décrire : Mon frère est grand. Ne mélangez pas.",
      "mon + masculin (mon frère), ma + féminin (ma sœur), mes + pluriel (mes parents). son/sa/ses suivent le nom, pas le genre du possesseur.",
      "Chez mes parents = at my parents' home. Ma sœur s'appelle Sophie. Mon frère s'appelle Lucas.",
      "Ma famille : mon père, ma mère, mon frère, ma sœur. Mon frère s'appelle Lucas. Ma sœur s'appelle Sophie. Mes parents habitent à Lyon. Mon père est français. Ma mère est italienne. Les possessifs mon, ma, mes décrivent qui appartient à qui.",
    ], V),
    conversation: {
      title: "Descriptions with être practice",
      setting: "Descriptions with être practice",
      lines: [
        conversationLine("Ami", "Tu as des frères ?", 'c4b-l0', V),
        conversationLine("Toi", "Oui, j'ai un frère.", 'c4b-l1', V),
        conversationLine("Ami", "Il est comment ?", 'c4b-l2', V),
        conversationLine("Toi", "Il est grand.", 'c4b-l3', V),
        conversationLine("Ami", "Et ta sœur ?", 'c4b-l4', V),
        conversationLine("Toi", "Elle est jeune.", 'c4b-l5', V),
        conversationLine("Ami", "Comment s'appelle-t-elle ?", 'c4b-l6', V),
        conversationLine("Toi", "Elle s'appelle Sophie.", 'c4b-l7', V),
        conversationLine("Ami", "Tes parents ?", 'c4b-l8', V),
        conversationLine("Toi", "Ils sont français.", 'c4b-l9', V),
        conversationLine("Ami", "Ils habitent où ?", 'c4b-l10', V),
        conversationLine("Toi", "À Lyon.", 'c4b-l11', V),
        conversationLine("Ami", "Merci !", 'c4b-l12', V),
        conversationLine("Toi", "De rien.", 'c4b-l13', V),
      ],
    },
    exercises: [
      {
        id: 'c4b-e1',
        category: "family",
        prompt: "frère =",
        options: ["brother", "father", "mother"],
        answer: 0,
        explanation: "brother",
      },
      {
        id: 'c4b-e2',
        category: "family",
        prompt: "père =",
        options: ["father", "sister", "tea"],
        answer: 0,
        explanation: "father",
      },
      {
        id: 'c4b-e3',
        category: "possessives",
        prompt: "my sister:",
        options: ["ma sœur", "mon sœur", "mes sœur"],
        answer: 0,
        explanation: "ma",
      },
      {
        id: 'c4b-e4',
        category: "\u00eatre-present",
        prompt: "Mon père est grand",
        options: ["description", "bill", "age with être wrong"],
        answer: 0,
        explanation: "être describe",
      },
      {
        id: 'c4b-e5',
        category: "family",
        prompt: "sœur =",
        options: ["sister", "brother", "sugar"],
        answer: 0,
        explanation: "sister",
      },
      {
        id: 'c4b-e6',
        category: "possessives",
        prompt: "mes parents",
        options: ["my parents", "your parents", "the bill"],
        answer: 0,
        explanation: "mes",
      },
      {
        id: 'c4b-e7',
        category: "family",
        prompt: "mère =",
        options: ["mother", "father", "Monday"],
        answer: 0,
        explanation: "mother",
      },
      {
        id: 'c4b-e8',
        category: "\u00eatre-present",
        prompt: "Ma sœur est jeune",
        options: ["My sister is young", "I have young", "Pay young"],
        answer: 0,
        explanation: "young",
      },
      {
        id: 'c4b-e9',
        category: "possessives",
        prompt: "mon frère",
        options: ["my brother", "my sister", "the tea"],
        answer: 0,
        explanation: "mon",
      },
      {
        id: 'c4b-e10',
        category: "family",
        prompt: "parents =",
        options: ["parents", "tea", "bill"],
        answer: 0,
        explanation: "parents",
      },
      {
        id: 'c4b-e11',
        category: "avoir-family",
        prompt: "J'ai un frère",
        options: ["I have a brother", "I am a brother", "I live brother"],
        answer: 0,
        explanation: "avoir",
      },
      {
        id: 'c4b-e12',
        category: "possessives",
        prompt: "son/sa follow:",
        options: ["the noun owned", "owner gender only", "days"],
        answer: 0,
        explanation: "owned",
      },
      {
        id: 'c4b-e13',
        category: "family",
        prompt: "fille =",
        options: ["daughter", "father", "tea"],
        answer: 0,
        explanation: "daughter",
      },
      {
        id: 'c4b-e14',
        category: "\u00eatre-present",
        prompt: "Ils sont français",
        options: ["They are French", "They have French", "They order"],
        answer: 0,
        explanation: "sont",
      },
      {
        id: 'c4b-e15',
        category: "family",
        prompt: "oncle =",
        options: ["uncle", "aunt", "tea"],
        answer: 0,
        explanation: "uncle",
      },
      {
        id: 'c4b-e16',
        category: "possessives",
        prompt: "ta sœur",
        options: ["your sister informal", "my sister", "bill"],
        answer: 0,
        explanation: "ta",
      },
      {
        id: 'c4b-e17',
        category: "family",
        prompt: "tante =",
        options: ["aunt", "uncle", "week"],
        answer: 0,
        explanation: "aunt",
      },
      {
        id: 'c4b-e18',
        category: "\u00eatre-present",
        prompt: "est =",
        options: ["is", "are we", "have"],
        answer: 0,
        explanation: "est",
      },
      {
        id: 'c4b-e19',
        category: "family",
        prompt: "cousin =",
        options: ["male cousin", "bill", "tea"],
        answer: 0,
        explanation: "cousin",
      },
      {
        id: 'c4b-e20',
        category: "possessives",
        prompt: "ma mère",
        options: ["my mother", "my father", "the day"],
        answer: 0,
        explanation: "ma",
      },
      {
        id: 'c4b-e21',
        category: "family",
        prompt: "grand-mère =",
        options: ["grandmother", "grandfather", "tea"],
        answer: 0,
        explanation: "grandmother",
      },
      {
        id: 'c4b-e22',
        category: "identity",
        prompt: "s'appelle",
        options: ["is called", "pays", "lives only"],
        answer: 0,
        explanation: "name",
      },
    ],
    wordCount: 233,
  },
  '22222222-0000-0000-0000-000000000142': {
    brief: {
      title: "Checkpoint: family tree",
      body: "What this lesson is for: mix family words, possessives, and short descriptions.\n\n**1. Words to learn first (meanings)**\nReview *père/mère/frère/sœur/parents*, *mon/ma/mes*, *avoir*, *être*, *chez*.\n\n**2. Tree talk:** who you have + how they are + names.",
      ruleSlugs: ["possessive-adjectives", "numbers-and-age"],
    },
    reading: readingParagraphs('c4c', [
      "Arbre simple : Mon père s'appelle Pierre. Ma mère s'appelle Claire. J'ai un frère et une sœur. Mon frère est grand. Ma sœur est jeune.",
      "Mes parents habitent à Lyon. Je vais chez mes parents le dimanche. J'ai aussi un oncle et une tante. Mon cousin s'appelle Lucas.",
      "Rappel sens : frère = brother, sœur = sister, père = father, mère = mother. Sans ces sens, mon frère est vide.",
      "Questions utiles : Tu as des frères et sœurs ? Comment s'appelle ta sœur ? Tes parents habitent où ?",
      "Tu as des frères et sœurs ? Oui, j'ai un frère et une sœur. Comment s'appelle ta sœur ? Elle s'appelle Marie. Tes parents habitent où ? Ils habitent à Paris. Il est grand, elle est petite — être + adjectif pour décrire. Reliez les membres de la famille avec mon, ma, son, sa.",
    ], V),
    conversation: {
      title: "Checkpoint: family tree practice",
      setting: "Checkpoint: family tree practice",
      lines: [
        conversationLine("Ami", "Tu as des frères et sœurs ?", 'c4c-l0', V),
        conversationLine("Toi", "Oui, un frère et une sœur.", 'c4c-l1', V),
        conversationLine("Ami", "Comment s'appelle ton frère ?", 'c4c-l2', V),
        conversationLine("Toi", "Lucas.", 'c4c-l3', V),
        conversationLine("Ami", "Et ta sœur ?", 'c4c-l4', V),
        conversationLine("Toi", "Sophie.", 'c4c-l5', V),
        conversationLine("Ami", "Tes parents ?", 'c4c-l6', V),
        conversationLine("Toi", "Pierre et Claire.", 'c4c-l7', V),
        conversationLine("Ami", "Ils habitent où ?", 'c4c-l8', V),
        conversationLine("Toi", "À Lyon.", 'c4c-l9', V),
        conversationLine("Ami", "Tu vas chez eux ?", 'c4c-l10', V),
        conversationLine("Toi", "Oui, le dimanche.", 'c4c-l11', V),
        conversationLine("Ami", "Super.", 'c4c-l12', V),
        conversationLine("Toi", "Et toi ?", 'c4c-l13', V),
      ],
    },
    exercises: [
      {
        id: 'c4c-e1',
        category: "family",
        prompt: "frère first means:",
        options: ["brother", "then grammar", "bill"],
        answer: 0,
        explanation: "meaning first",
      },
      {
        id: 'c4c-e2',
        category: "possessives",
        prompt: "mon père",
        options: ["my father", "my mother", "tea"],
        answer: 0,
        explanation: "mon",
      },
      {
        id: 'c4c-e3',
        category: "family",
        prompt: "sœur =",
        options: ["sister", "brother", "week"],
        answer: 0,
        explanation: "sister",
      },
      {
        id: 'c4c-e4',
        category: "avoir-family",
        prompt: "J'ai une sœur",
        options: ["I have a sister", "I am sister", "I live"],
        answer: 0,
        explanation: "avoir",
      },
      {
        id: 'c4c-e5',
        category: "possessives",
        prompt: "mes frères",
        options: ["my brothers", "my sister", "bill"],
        answer: 0,
        explanation: "mes",
      },
      {
        id: 'c4c-e6',
        category: "family",
        prompt: "chez mes parents",
        options: ["at my parents' home", "I am parents", "pay"],
        answer: 0,
        explanation: "chez",
      },
      {
        id: 'c4c-e7',
        category: "\u00eatre-present",
        prompt: "Ma mère est française",
        options: ["description", "bill", "age wrong"],
        answer: 0,
        explanation: "être",
      },
      {
        id: 'c4c-e8',
        category: "family",
        prompt: "oncle =",
        options: ["uncle", "aunt", "tea"],
        answer: 0,
        explanation: "uncle",
      },
      {
        id: 'c4c-e9',
        category: "possessives",
        prompt: "sa mère",
        options: ["his/her mother", "my mother always", "bill"],
        answer: 0,
        explanation: "sa",
      },
      {
        id: 'c4c-e10',
        category: "family",
        prompt: "cousine =",
        options: ["female cousin", "male cousin", "tea"],
        answer: 0,
        explanation: "cousine",
      },
      {
        id: 'c4c-e11',
        category: "numbers-and-age",
        prompt: "deux sœurs",
        options: ["two sisters", "Tuesday sisters", "bill"],
        answer: 0,
        explanation: "deux",
      },
      {
        id: 'c4c-e12',
        category: "family",
        prompt: "grand-père =",
        options: ["grandfather", "grandmother", "tea"],
        answer: 0,
        explanation: "grandfather",
      },
      {
        id: 'c4c-e13',
        category: "possessives",
        prompt: "ton frère",
        options: ["your brother", "my brother", "tea"],
        answer: 0,
        explanation: "ton",
      },
      {
        id: 'c4c-e14',
        category: "identity",
        prompt: "s'appelle Sophie",
        options: ["is called Sophie", "pays Sophie", "lives Sophie"],
        answer: 0,
        explanation: "name",
      },
      {
        id: 'c4c-e15',
        category: "family",
        prompt: "parents =",
        options: ["parents", "tea", "bill"],
        answer: 0,
        explanation: "parents",
      },
      {
        id: 'c4c-e16',
        category: "\u00eatre-present",
        prompt: "est jeune",
        options: ["is young", "has young", "orders"],
        answer: 0,
        explanation: "est",
      },
      {
        id: 'c4c-e17',
        category: "family",
        prompt: "fille =",
        options: ["daughter", "father", "Monday"],
        answer: 0,
        explanation: "daughter",
      },
      {
        id: 'c4c-e18',
        category: "possessives",
        prompt: "ma =",
        options: ["my (f.)", "my (m.)", "they"],
        answer: 0,
        explanation: "ma",
      },
      {
        id: 'c4c-e19',
        category: "family",
        prompt: "mari =",
        options: ["husband", "wife", "tea"],
        answer: 0,
        explanation: "husband",
      },
      {
        id: 'c4c-e20',
        category: "family",
        prompt: "femme =",
        options: ["wife/woman", "father", "week"],
        answer: 0,
        explanation: "wife",
      },
      {
        id: 'c4c-e21',
        category: "avoir-family",
        prompt: "Elle a deux frères",
        options: ["She has two brothers", "She is two", "She lives two"],
        answer: 0,
        explanation: "avoir",
      },
      {
        id: 'c4c-e22',
        category: "family",
        prompt: "tante =",
        options: ["aunt", "uncle", "tea"],
        answer: 0,
        explanation: "aunt",
      },
    ],
    wordCount: 233,
  },
  '22222222-0000-0000-0000-000000000151': {
    brief: {
      title: "Alphabet & accents",
      body: "What this lesson is for: French letters and accent marks with meanings first.\n\n**1. Words to learn first (meanings)**\n- *alphabet* = alphabet · *lettre* = letter · *accent* = accent mark\n- *aigu* (é) = acute · *grave* (è) = grave · *circonflexe* (ê) = circumflex · *tréma* (ë) = diaeresis\n- *ç* (*cédille*) = cedilla (makes /s/ sound before a/o/u)\n\n**2. Why it matters:** accents change sound and meaning (*a* vs *à*, *ou* vs *où*).\n**3. Practice:** name accents and read simple words aloud in your head.",
      ruleSlugs: ["silent-final-consonants"],
    },
    reading: readingParagraphs('c5a', [
      "L'alphabet français ressemble à l'alphabet anglais, mais les accents comptent. é = accent aigu. è = accent grave. ê = accent circonflexe. ë = tréma.",
      "Exemples : café (é), père (è), être (ê), Noël (ë). La cédille ç donne un son /s/ : français, ça.",
      "À (with grave) can mean “at/to”. A without accent is the verb form “has”. Où means “where”; ou means “or”.",
      "Apprenez les noms des signes. Quand vous lisez un mot nouveau, regardez les accents avant de deviner. Les lettres silencieuses viennent dans la leçon suivante.",
      "L'alphabet français a vingt-six lettres, comme en anglais, mais les accents changent le son. é, è, ê, ç — chaque signe compte à l'écrit. Où habites-tu ? Où avec accent ; ou sans accent veut dire or. À Paris, on voit beaucoup d'accents sur les panneaux.",
    ], V),
    conversation: {
      title: "Alphabet & accents practice",
      setting: "Alphabet & accents practice",
      lines: [
        conversationLine("Prof", "Qu'est-ce que c'est ?", 'c5a-l0', V),
        conversationLine("\u00c9l\u00e8ve", "Un accent aigu.", 'c5a-l1', V),
        conversationLine("Prof", "Et ça ?", 'c5a-l2', V),
        conversationLine("\u00c9l\u00e8ve", "Un accent grave.", 'c5a-l3', V),
        conversationLine("Prof", "Café a quel accent ?", 'c5a-l4', V),
        conversationLine("\u00c9l\u00e8ve", "Aigu.", 'c5a-l5', V),
        conversationLine("Prof", "Père ?", 'c5a-l6', V),
        conversationLine("\u00c9l\u00e8ve", "Grave.", 'c5a-l7', V),
        conversationLine("Prof", "Être ?", 'c5a-l8', V),
        conversationLine("\u00c9l\u00e8ve", "Circonflexe.", 'c5a-l9', V),
        conversationLine("Prof", "Français a une…", 'c5a-l10', V),
        conversationLine("\u00c9l\u00e8ve", "Cédille.", 'c5a-l11', V),
        conversationLine("Prof", "Bien !", 'c5a-l12', V),
        conversationLine("\u00c9l\u00e8ve", "Merci !", 'c5a-l13', V),
      ],
    },
    exercises: [
      {
        id: 'c5a-e1',
        category: "silent-final-consonants",
        prompt: "é is:",
        options: ["acute accent", "silent father", "bill"],
        answer: 0,
        explanation: "acute",
      },
      {
        id: 'c5a-e2',
        category: "silent-final-consonants",
        prompt: "è is:",
        options: ["grave", "acute", "cedilla"],
        answer: 0,
        explanation: "grave",
      },
      {
        id: 'c5a-e3',
        category: "silent-final-consonants",
        prompt: "ê is:",
        options: ["circumflex", "acute", "tea only"],
        answer: 0,
        explanation: "circumflex",
      },
      {
        id: 'c5a-e4',
        category: "vocab-meaning",
        prompt: "où =",
        options: ["where", "or", "father"],
        answer: 0,
        explanation: "where",
      },
      {
        id: 'c5a-e5',
        category: "vocab-meaning",
        prompt: "ou =",
        options: ["or", "where", "bill"],
        answer: 0,
        explanation: "or",
      },
      {
        id: 'c5a-e6',
        category: "silent-final-consonants",
        prompt: "ç gives:",
        options: ["/s/ sound", "/k/ only", "age"],
        answer: 0,
        explanation: "cedilla",
      },
      {
        id: 'c5a-e7',
        category: "vocab-meaning",
        prompt: "café has:",
        options: ["é", "è", "ç"],
        answer: 0,
        explanation: "é",
      },
      {
        id: 'c5a-e8',
        category: "vocab-meaning",
        prompt: "père has:",
        options: ["è", "é", "ô"],
        answer: 0,
        explanation: "è",
      },
      {
        id: 'c5a-e9',
        category: "silent-final-consonants",
        prompt: "alphabet =",
        options: ["alphabet", "brother", "tea"],
        answer: 0,
        explanation: "alphabet",
      },
      {
        id: 'c5a-e10',
        category: "vocab-meaning",
        prompt: "lettre =",
        options: ["letter", "bill", "week"],
        answer: 0,
        explanation: "letter",
      },
      {
        id: 'c5a-e11',
        category: "silent-final-consonants",
        prompt: "tréma example:",
        options: ["Noël", "bonjour", "père only"],
        answer: 0,
        explanation: "Noël",
      },
      {
        id: 'c5a-e12',
        category: "vocab-meaning",
        prompt: "à can mean:",
        options: ["at/to", "always has", "brother"],
        answer: 0,
        explanation: "at",
      },
      {
        id: 'c5a-e13',
        category: "vocab-meaning",
        prompt: "français needs:",
        options: ["ç", "only é", "no accents"],
        answer: 0,
        explanation: "ç",
      },
      {
        id: 'c5a-e14',
        category: "silent-final-consonants",
        prompt: "Accents can change:",
        options: ["meaning", "only color", "the bill"],
        answer: 0,
        explanation: "meaning",
      },
      {
        id: 'c5a-e15',
        category: "greetings",
        prompt: "bonjour",
        options: ["hello", "accent name", "father"],
        answer: 0,
        explanation: "hello",
      },
      {
        id: 'c5a-e16',
        category: "vocab-meaning",
        prompt: "être has:",
        options: ["ê", "only è", "ç"],
        answer: 0,
        explanation: "ê",
      },
      {
        id: 'c5a-e17',
        category: "silent-final-consonants",
        prompt: "acute name in FR:",
        options: ["aigu", "grave", "cedille"],
        answer: 0,
        explanation: "aigu",
      },
      {
        id: 'c5a-e18',
        category: "silent-final-consonants",
        prompt: "grave name:",
        options: ["grave", "aigu", "circonflexe"],
        answer: 0,
        explanation: "grave",
      },
      {
        id: 'c5a-e19',
        category: "vocab-meaning",
        prompt: "ça uses:",
        options: ["ç", "é only", "è only"],
        answer: 0,
        explanation: "ç",
      },
      {
        id: 'c5a-e20',
        category: "silent-final-consonants",
        prompt: "Look for accents:",
        options: ["before guessing sound", "never", "only in English"],
        answer: 0,
        explanation: "look",
      },
      {
        id: 'c5a-e21',
        category: "vocab-meaning",
        prompt: "circonflexe =",
        options: ["circumflex", "brother", "tea"],
        answer: 0,
        explanation: "circumflex",
      },
      {
        id: 'c5a-e22',
        category: "vocab-meaning",
        prompt: "cédille =",
        options: ["cedilla", "grandmother", "Monday"],
        answer: 0,
        explanation: "cedilla",
      },
    ],
    wordCount: 233,
  },
  '22222222-0000-0000-0000-000000000152': {
    brief: {
      title: "Silent letters",
      body: "What this lesson is for: hear that many final consonants are silent.\n\n**1. Words to learn first (meanings)**\n- *silent* idea: final *-s, -t, -d, -x* often not pronounced\n- Examples: *vous* (final s soft/silent), *petit* (final t often silent), *grand* (d often silent)\n- *liaison* = linking: sometimes a silent letter is pronounced before a vowel (*vous êtes*)\n\n**2. Spelling still shows the letter** even when speech drops it.\n**3. Practice:** compare singular/plural forms in writing.",
      ruleSlugs: ["silent-final-consonants"],
    },
    reading: readingParagraphs('c5b', [
      "En français, beaucoup de consonnes finales sont silencieuses. Dans petit, le t final est souvent muet. Dans grand, le d final est souvent muet. Dans vous, le s final est souvent muet.",
      "Mais l'orthographe garde les lettres. petit / petite : on écrit t dans les deux. Au pluriel : petits, petites.",
      "Liaison : vous êtes — on peut entendre un /z/ entre vous et êtes. La lettre “silencieuse” revient devant une voyelle.",
      "Exemples utiles : francais/français spelling with ç; ils parlent ends with -ent often silent. Écoutez et regardez l'écrit ensemble.",
      "À l'écrit : parents, français, vous êtes. À l'oral, les lettres finales sont souvent silencieuses. Vous êtes peut avoir une liaison. Le mot café garde le e à la fin à l'écrit. Écoutez et lisez ensemble : il parle, elle habite, ils sont.",
    ], V),
    conversation: {
      title: "Silent letters practice",
      setting: "Silent letters practice",
      lines: [
        conversationLine("Prof", "Le t de petit ?", 'c5b-l0', V),
        conversationLine("\u00c9l\u00e8ve", "Souvent silencieux.", 'c5b-l1', V),
        conversationLine("Prof", "Et petite ?", 'c5b-l2', V),
        conversationLine("\u00c9l\u00e8ve", "On entend le t.", 'c5b-l3', V),
        conversationLine("Prof", "vous êtes — liaison ?", 'c5b-l4', V),
        conversationLine("\u00c9l\u00e8ve", "Oui, parfois /z/.", 'c5b-l5', V),
        conversationLine("Prof", "ils parlent — ent ?", 'c5b-l6', V),
        conversationLine("\u00c9l\u00e8ve", "Souvent silencieux.", 'c5b-l7', V),
        conversationLine("Prof", "On écrit quand même ?", 'c5b-l8', V),
        conversationLine("\u00c9l\u00e8ve", "Oui.", 'c5b-l9', V),
        conversationLine("Prof", "Bien.", 'c5b-l10', V),
        conversationLine("\u00c9l\u00e8ve", "Merci.", 'c5b-l11', V),
        conversationLine("Prof", "Autre exemple : grand.", 'c5b-l12', V),
        conversationLine("\u00c9l\u00e8ve", "d souvent muet.", 'c5b-l13', V),
      ],
    },
    exercises: [
      {
        id: 'c5b-e1',
        category: "silent-final-consonants",
        prompt: "Final -t in petit often:",
        options: ["silent", "always loud", "English"],
        answer: 0,
        explanation: "silent",
      },
      {
        id: 'c5b-e2',
        category: "silent-final-consonants",
        prompt: "petite often:",
        options: ["pronounces t", "drops all letters", "bill"],
        answer: 0,
        explanation: "t heard",
      },
      {
        id: 'c5b-e3',
        category: "silent-final-consonants",
        prompt: "liaison =",
        options: ["linking before vowel", "paying", "age"],
        answer: 0,
        explanation: "liaison",
      },
      {
        id: 'c5b-e4',
        category: "silent-final-consonants",
        prompt: "vous êtes may hear:",
        options: ["/z/ link", "only English", "father"],
        answer: 0,
        explanation: "z",
      },
      {
        id: 'c5b-e5',
        category: "silent-final-consonants",
        prompt: "Write silent letters?",
        options: ["yes", "never", "only numbers"],
        answer: 0,
        explanation: "yes",
      },
      {
        id: 'c5b-e6',
        category: "silent-final-consonants",
        prompt: "ils parlent -ent:",
        options: ["often silent", "always stressed", "tea"],
        answer: 0,
        explanation: "silent",
      },
      {
        id: 'c5b-e7',
        category: "silent-final-consonants",
        prompt: "grand final d:",
        options: ["often silent", "always /d/", "bill"],
        answer: 0,
        explanation: "silent",
      },
      {
        id: 'c5b-e8',
        category: "vocab-meaning",
        prompt: "petit =",
        options: ["small", "father", "tea"],
        answer: 0,
        explanation: "small",
      },
      {
        id: 'c5b-e9',
        category: "vocab-meaning",
        prompt: "grand =",
        options: ["tall/big", "tea", "week"],
        answer: 0,
        explanation: "tall",
      },
      {
        id: 'c5b-e10',
        category: "silent-final-consonants",
        prompt: "Orthography vs speech:",
        options: ["can differ", "identical always", "English only"],
        answer: 0,
        explanation: "differ",
      },
      {
        id: 'c5b-e11',
        category: "\u00eatre-present",
        prompt: "vous êtes",
        options: ["you are", "we are", "they are"],
        answer: 0,
        explanation: "êtes",
      },
      {
        id: 'c5b-e12',
        category: "silent-final-consonants",
        prompt: "Plural spelling keeps:",
        options: ["-s often", "no letters", "bills"],
        answer: 0,
        explanation: "-s",
      },
      {
        id: 'c5b-e13',
        category: "vocab-meaning",
        prompt: "parler =",
        options: ["to speak", "to pay", "to live"],
        answer: 0,
        explanation: "speak",
      },
      {
        id: 'c5b-e14',
        category: "silent-final-consonants",
        prompt: "Before vowel, silent letter may:",
        options: ["sound in liaison", "disappear from spelling", "become age"],
        answer: 0,
        explanation: "liaison",
      },
      {
        id: 'c5b-e15',
        category: "greetings",
        prompt: "vous",
        options: ["you formal/plural", "father", "tea"],
        answer: 0,
        explanation: "vous",
      },
      {
        id: 'c5b-e16',
        category: "silent-final-consonants",
        prompt: "Train ear + eye",
        options: ["true", "false", "bill"],
        answer: 0,
        explanation: "true",
      },
      {
        id: 'c5b-e17',
        category: "vocab-meaning",
        prompt: "muet ≈",
        options: ["silent", "loud", "Monday"],
        answer: 0,
        explanation: "silent",
      },
      {
        id: 'c5b-e18',
        category: "silent-final-consonants",
        prompt: "français ç is:",
        options: ["not the silent-final topic", "a bill", "a day"],
        answer: 0,
        explanation: "different topic",
      },
      {
        id: 'c5b-e19',
        category: "\u00eatre-present",
        prompt: "ils sont",
        options: ["they are", "I am", "we pay"],
        answer: 0,
        explanation: "sont",
      },
      {
        id: 'c5b-e20',
        category: "silent-final-consonants",
        prompt: "petite vs petit",
        options: ["gender spelling/sound", "same always", "tea"],
        answer: 0,
        explanation: "gender",
      },
      {
        id: 'c5b-e21',
        category: "vocab-meaning",
        prompt: "lettre =",
        options: ["letter", "bill", "sister"],
        answer: 0,
        explanation: "letter",
      },
      {
        id: 'c5b-e22',
        category: "silent-final-consonants",
        prompt: "Final -x often:",
        options: ["silent", "always /ks/", "father"],
        answer: 0,
        explanation: "silent",
      },
    ],
    wordCount: 235,
  },
  '22222222-0000-0000-0000-000000000153': {
    brief: {
      title: "Checkpoint: spelling names",
      body: "What this lesson is for: spell and notice accents/silent letters in names and words.\n\n**1. Words to learn first (meanings)**\nReview accent names and silent finals. *s'appeler* = to be called. *comment ça s'écrit ?* = how do you spell that?\n\n**2. Chunk:** *Ça s'écrit comment ?* / *Comment ça s'écrit ?*",
      ruleSlugs: ["silent-final-consonants"],
    },
    reading: readingParagraphs('c5c', [
      "On épelle des noms. Sophie : S-O-P-H-I-E. François : attention à ç. Hélène : attention à è et à l'accent.",
      "Comment ça s'écrit ? On répond lettre par lettre. Les accents font partie de l'orthographe. Un é n'est pas un è.",
      "Dans vous et ils, les lettres finales restent à l'écrit. À l'oral, elles sont souvent silencieuses, sauf liaison.",
      "Checkpoint : reliez sons, accents et lettres silencieuses. Lisez à voix haute dans votre tête : café, père, être, français, vous êtes.",
      "Comment ça s'écrit ? M-A-R-I-E. Mon nom est Dubois : D-U-B-O-I-S. Les lettres et les accents servent à épeler. Français avec ç ; père avec accent grave. Répétez : Je m'appelle…, Comment tu t'appelles ?, Enchanté.",
    ], V),
    conversation: {
      title: "Checkpoint: spelling names practice",
      setting: "Checkpoint: spelling names practice",
      lines: [
        conversationLine("Ami", "Comment ça s'écrit, Sophie ?", 'c5c-l0', V),
        conversationLine("Toi", "S-O-P-H-I-E.", 'c5c-l1', V),
        conversationLine("Ami", "Et François ?", 'c5c-l2', V),
        conversationLine("Toi", "Avec une cédille.", 'c5c-l3', V),
        conversationLine("Ami", "Hélène ?", 'c5c-l4', V),
        conversationLine("Toi", "Avec un accent grave.", 'c5c-l5', V),
        conversationLine("Ami", "café ?", 'c5c-l6', V),
        conversationLine("Toi", "Accent aigu.", 'c5c-l7', V),
        conversationLine("Ami", "être ?", 'c5c-l8', V),
        conversationLine("Toi", "Circonflexe.", 'c5c-l9', V),
        conversationLine("Ami", "vous êtes — liaison ?", 'c5c-l10', V),
        conversationLine("Toi", "Oui, possible.", 'c5c-l11', V),
        conversationLine("Ami", "Merci !", 'c5c-l12', V),
        conversationLine("Toi", "De rien.", 'c5c-l13', V),
      ],
    },
    exercises: [
      {
        id: 'c5c-e1',
        category: "silent-final-consonants",
        prompt: "café accent:",
        options: ["aigu", "grave", "cedilla"],
        answer: 0,
        explanation: "aigu",
      },
      {
        id: 'c5c-e2',
        category: "silent-final-consonants",
        prompt: "père accent:",
        options: ["grave", "aigu", "none"],
        answer: 0,
        explanation: "grave",
      },
      {
        id: 'c5c-e3',
        category: "silent-final-consonants",
        prompt: "être accent:",
        options: ["circonflexe", "aigu", "none"],
        answer: 0,
        explanation: "circonflexe",
      },
      {
        id: 'c5c-e4',
        category: "silent-final-consonants",
        prompt: "François needs:",
        options: ["ç", "only é", "no mark"],
        answer: 0,
        explanation: "ç",
      },
      {
        id: 'c5c-e5',
        category: "identity",
        prompt: "Comment ça s'écrit ?",
        options: ["How do you spell it?", "How old?", "Where live?"],
        answer: 0,
        explanation: "spell",
      },
      {
        id: 'c5c-e6',
        category: "silent-final-consonants",
        prompt: "vous êtes liaison",
        options: ["possible /z/", "never", "bill"],
        answer: 0,
        explanation: "liaison",
      },
      {
        id: 'c5c-e7',
        category: "vocab-meaning",
        prompt: "Hélène has:",
        options: ["è", "only é", "ç"],
        answer: 0,
        explanation: "è",
      },
      {
        id: 'c5c-e8',
        category: "silent-final-consonants",
        prompt: "Spell accents?",
        options: ["yes they matter", "never", "only English"],
        answer: 0,
        explanation: "yes",
      },
      {
        id: 'c5c-e9',
        category: "greetings",
        prompt: "merci",
        options: ["thank you", "spell", "tea"],
        answer: 0,
        explanation: "thanks",
      },
      {
        id: 'c5c-e10',
        category: "silent-final-consonants",
        prompt: "ils — final letters",
        options: ["written often silent", "deleted", "bill"],
        answer: 0,
        explanation: "written",
      },
      {
        id: 'c5c-e11',
        category: "vocab-meaning",
        prompt: "Sophie is:",
        options: ["a name", "a partitive", "a day"],
        answer: 0,
        explanation: "name",
      },
      {
        id: 'c5c-e12',
        category: "silent-final-consonants",
        prompt: "aigu =",
        options: ["acute", "grave", "week"],
        answer: 0,
        explanation: "acute",
      },
      {
        id: 'c5c-e13',
        category: "silent-final-consonants",
        prompt: "grave =",
        options: ["grave accent", "bill", "tea"],
        answer: 0,
        explanation: "grave",
      },
      {
        id: 'c5c-e14',
        category: "silent-final-consonants",
        prompt: "cédille =",
        options: ["cedilla", "father", "Monday"],
        answer: 0,
        explanation: "cedilla",
      },
      {
        id: 'c5c-e15',
        category: "\u00eatre-present",
        prompt: "êtes",
        options: ["are (vous)", "am", "has"],
        answer: 0,
        explanation: "êtes",
      },
      {
        id: 'c5c-e16',
        category: "vocab-meaning",
        prompt: "lettre =",
        options: ["letter", "sister", "tea"],
        answer: 0,
        explanation: "letter",
      },
      {
        id: 'c5c-e17',
        category: "silent-final-consonants",
        prompt: "Read café aloud carefully",
        options: ["true", "false", "bill"],
        answer: 0,
        explanation: "true",
      },
      {
        id: 'c5c-e18',
        category: "identity",
        prompt: "s'appeler",
        options: ["to be called", "to pay", "to live only"],
        answer: 0,
        explanation: "called",
      },
      {
        id: 'c5c-e19',
        category: "silent-final-consonants",
        prompt: "ou vs où",
        options: ["or vs where", "same", "bill"],
        answer: 0,
        explanation: "diff",
      },
      {
        id: 'c5c-e20',
        category: "greetings",
        prompt: "bonjour",
        options: ["hello", "accent", "father"],
        answer: 0,
        explanation: "hello",
      },
      {
        id: 'c5c-e21',
        category: "silent-final-consonants",
        prompt: "Checkpoint mixes:",
        options: ["accents + silent + spelling", "only plot", "only tea"],
        answer: 0,
        explanation: "mix",
      },
      {
        id: 'c5c-e22',
        category: "vocab-meaning",
        prompt: "français",
        options: ["French", "bill", "week"],
        answer: 0,
        explanation: "French",
      },
    ],
    wordCount: 224,
  },
}
}
