import type { LessonExercise } from '@/lib/exercises/types'

/** Varied supplemental exercises keyed by chapter id. */
export const CHAPTER_EXERCISE_EXTRAS: Record<string, LessonExercise[]> = {
  '22222222-0000-0000-0000-000000000101': [
    {
      id: 'c1-x-cloze1',
      type: 'cloze',
      category: 'être-present',
      source: 'grammar',
      text: 'Je ___ français.',
      answers: ['suis'],
      prompt: 'Type the missing word.',
      explanation: 'Je suis is the first-person form of être.',
      hint: 'Think: je + être in the present.',
    },
    {
      id: 'c1-x-cloze2',
      type: 'cloze',
      category: 'habiter',
      source: 'grammar',
      text: "J'___ à Paris.",
      answers: ['habite'],
      prompt: 'Type the verb form.',
      explanation: "J'habite — habiter with je drops the e before a vowel.",
    },
    {
      id: 'c1-x-spot1',
      type: 'spot-error',
      category: 'cest-versus-il-est',
      source: 'grammar',
      sentence: 'Il est Marc.',
      words: ['Il', 'est', 'Marc.'],
      errorIndex: 0,
      prompt: 'Tap the word that should change to identify someone by name.',
      explanation: 'For a name use C\'est Marc, not Il est Marc.',
    },
    {
      id: 'c1-x-spot2',
      type: 'spot-error',
      category: 'cest-versus-il-est',
      source: 'grammar',
      sentence: "C'est française.",
      words: ['C\'est', 'française.'],
      errorIndex: 0,
      prompt: 'Which part is wrong?',
      explanation: 'Never c\'est + adjective alone — use Elle est française.',
    },
    {
      id: 'c1-x-match1',
      type: 'match',
      category: 'subject-pronouns',
      source: 'grammar',
      left: ['je', 'tu', 'nous', 'vous'],
      right: ['I', 'you (informal)', 'we', 'you (formal/plural)'],
      pairs: [[0, 0], [1, 1], [2, 2], [3, 3]],
      prompt: 'Match each pronoun to its English meaning.',
      explanation: 'French subject pronouns must match who is speaking.',
    },
    {
      id: 'c1-x-order1',
      type: 'order',
      category: 'identity',
      source: 'grammar',
      words: ["m'appelle", 'Je', 'Marc.'],
      answer: ['Je', "m'appelle", 'Marc.'],
      prompt: 'Put the words in order to introduce yourself.',
      explanation: 'Je m\'appelle + name.',
    },
    {
      id: 'c1-x-translate1',
      type: 'translate',
      category: 'greetings',
      source: 'grammar',
      direction: 'en-fr',
      answers: ['bonjour', 'Bonjour'],
      prompt: 'Translate to French: "Hello" (daytime).',
      explanation: 'Bonjour is used in the morning and afternoon.',
    },
    {
      id: 'c1-x-tf1',
      type: 'true-false',
      category: 'tu-vous',
      source: 'grammar',
      statement: 'With a stranger in a shop, tu is usually the safest choice.',
      answer: false,
      prompt: 'True or false?',
      explanation: 'Start with vous for strangers — tu is informal.',
    },
    {
      id: 'c1-x-conj1',
      type: 'conjugation',
      category: 'être-present',
      source: 'grammar',
      verb: 'être',
      tense: 'Présent',
      pronoun: 'nous',
      answers: ['sommes'],
      prompt: 'Conjugate être (Présent): nous ___',
      explanation: 'Nous sommes.',
    },
    {
      id: 'c1-x-register1',
      type: 'register',
      category: 'tu-vous',
      source: 'grammar',
      situation: 'You meet your professor for the first time.',
      options: ['Comment tu t\'appelles ?', 'Comment vous appelez-vous ?', 'Salut prof !'],
      answer: 1,
      prompt: 'Which question is appropriate?',
      explanation: 'Vous + Comment vous appelez-vous ? is formal and polite.',
    },
    {
      id: 'c1-x-minimal1',
      type: 'minimal-pair',
      category: 'cest-versus-il-est',
      source: 'grammar',
      options: ['C\'est Marc.', 'Il est Marc.', 'Je est Marc.'],
      answer: 0,
      prompt: 'Which sentence correctly identifies someone by name?',
      explanation: 'C\'est + name for identification.',
    },
    {
      id: 'c1-x-dialogue1',
      type: 'dialogue',
      category: 'conversation',
      source: 'dialogue',
      context: 'Someone introduces themselves: « Moi, c\'est Marie. » What is a natural follow-up?',
      options: ['Au revoir !', 'Tu es française ?', 'Bonne nuit.'],
      answer: 1,
      prompt: 'Choose the most natural next line.',
      explanation: 'After an introduction, asking about nationality is natural: Tu es française ?',
    },
    {
      id: 'c1-x-reading1',
      type: 'mcq',
      category: 'habiter',
      source: 'grammar',
      options: ['Elle habite à Lyon.', 'Elle est à Lyon.', 'Elle a Lyon.'],
      answer: 0,
      prompt: 'How do you say “She lives in Lyon”?',
      explanation: 'Habiter + à + city: Elle habite à Lyon.',
    },
  ],
  '22222222-0000-0000-0000-000000000102': [
    {
      id: 'c2-x-cloze1',
      type: 'cloze',
      category: 'avoir-age',
      source: 'grammar',
      text: "J'___ vingt ans.",
      answers: ['ai'],
      prompt: 'Type the missing word (avoir).',
      explanation: 'Age uses avoir: j\'ai vingt ans.',
    },
    {
      id: 'c2-x-cloze2',
      type: 'cloze',
      category: 'numbers',
      source: 'grammar',
      text: 'Demain, c\'est ___.',
      answers: ['mardi', 'Mardi'],
      prompt: 'If today is Monday, type the French for tomorrow\'s day.',
      explanation: 'The day after lundi is mardi.',
      hint: 'Check the brief on days of the week.',
    },
    {
      id: 'c2-x-match1',
      type: 'match',
      category: 'days',
      source: 'grammar',
      left: ['lundi', 'mercredi', 'samedi'],
      right: ['Monday', 'Wednesday', 'Saturday'],
      pairs: [[0, 0], [1, 1], [2, 2]],
      prompt: 'Match the days.',
      explanation: 'French weekdays are not capitalized unless they start a sentence.',
    },
    {
      id: 'c2-x-order1',
      type: 'order',
      category: 'time',
      source: 'grammar',
      words: ["aujourd'hui", 'c\'est', 'lundi.'],
      answer: ["Aujourd'hui", 'c\'est', 'lundi.'],
      prompt: 'Build: Today is Monday.',
      explanation: "Aujourd'hui, c'est lundi.",
    },
    {
      id: 'c2-x-translate1',
      type: 'translate',
      category: 'time',
      source: 'grammar',
      direction: 'en-fr',
      answers: ['demain', 'Demain'],
      prompt: 'Translate: "tomorrow"',
      explanation: 'Demain = tomorrow; hier = yesterday.',
    },
    {
      id: 'c2-x-tf1',
      type: 'true-false',
      category: 'avoir-age',
      source: 'grammar',
      statement: 'In French you say your age with être: Je suis vingt ans.',
      answer: false,
      prompt: 'True or false?',
      explanation: 'Use avoir: J\'ai vingt ans.',
    },
    {
      id: 'c2-x-conj1',
      type: 'conjugation',
      category: 'avoir-present',
      source: 'grammar',
      verb: 'avoir',
      tense: 'Présent',
      pronoun: 'tu',
      answers: ['as'],
      prompt: 'Conjugate avoir (Présent): tu ___',
      explanation: 'Tu as.',
    },
    {
      id: 'c2-x-register1',
      type: 'register',
      category: 'questions',
      source: 'grammar',
      situation: 'You ask a colleague (vous) their age politely.',
      options: ['Tu as quel âge ?', 'Quel âge avez-vous ?', 'Tu es quel âge ?'],
      answer: 1,
      prompt: 'Most polite form?',
      explanation: 'Quel âge avez-vous ? with vous.',
    },
    {
      id: 'c2-x-spot1',
      type: 'spot-error',
      category: 'avoir-age',
      source: 'grammar',
      sentence: 'Elle est quinze ans.',
      words: ['Elle', 'est', 'quinze', 'ans.'],
      errorIndex: 1,
      prompt: 'Find the wrong word.',
      explanation: 'Age needs avoir: Elle a quinze ans.',
    },
    {
      id: 'c2-x-dialogue1',
      type: 'dialogue',
      category: 'conversation',
      source: 'dialogue',
      context: 'Someone asks « Quel jour sommes-nous ? » — best answer?',
      options: ['J\'ai vingt ans.', 'Nous sommes lundi.', 'C\'est demain.'],
      answer: 1,
      prompt: 'Choose the natural reply.',
      explanation: 'Quel jour sommes-nous ? → Nous sommes lundi / C\'est lundi.',
    },
    {
      id: 'c2-x-reading1',
      type: 'cloze',
      category: 'numbers',
      source: 'grammar',
      text: 'Une année a ___ semaines.',
      answers: ['cinquante-deux', '52'],
      prompt: 'Type the number of weeks in a year (French).',
      explanation: 'Cinquante-deux semaines.',
    },
    {
      id: 'c2-x-minimal1',
      type: 'minimal-pair',
      category: 'time',
      source: 'grammar',
      options: ['Hier, c\'était dimanche.', 'Hier, c\'est dimanche.', 'Hier, il est dimanche.'],
      answer: 0,
      prompt: 'Which sentence about yesterday is correct?',
      explanation: 'Past reference: c\'était (imparfait of être in set phrases).',
    },
  ],
  '22222222-0000-0000-0000-000000000103': [
    {
      id: 'c3-x-cloze1',
      type: 'cloze',
      category: 'prendre',
      source: 'grammar',
      text: 'Je ___ un café.',
      answers: ['prends'],
      prompt: 'Conjugate prendre (je).',
      explanation: 'Je prends un café.',
    },
    {
      id: 'c3-x-cloze2',
      type: 'cloze',
      category: 'politeness',
      source: 'grammar',
      text: '___, un thé, s\'il vous plaît.',
      answers: ['Bonjour', 'bonjour'],
      prompt: 'What polite word opens an order at a café?',
      explanation: 'Always bonjour before ordering in France.',
    },
    {
      id: 'c3-x-match1',
      type: 'match',
      category: 'café-vocab',
      source: 'grammar',
      left: ['un café', 'une baguette', 'l\'addition'],
      right: ['coffee', 'bread', 'the bill'],
      pairs: [[0, 0], [1, 1], [2, 2]],
      prompt: 'Match café vocabulary.',
      explanation: 'L\'addition = the check/bill.',
    },
    {
      id: 'c3-x-order1',
      type: 'order',
      category: 'ordering',
      source: 'grammar',
      words: ['plaît', 'vous', 's\'il', 'un', 'café,'],
      answer: ['Un', 'café,', 's\'il', 'vous', 'plaît'],
      prompt: 'Order a coffee politely.',
      explanation: 'Un café, s\'il vous plaît.',
    },
    {
      id: 'c3-x-translate1',
      type: 'translate',
      category: 'politeness',
      source: 'grammar',
      direction: 'en-fr',
      answers: ['merci', 'Merci'],
      prompt: 'Translate: "thank you"',
      explanation: 'Merci — often merci beaucoup.',
    },
    {
      id: 'c3-x-tf1',
      type: 'true-false',
      category: 'articles',
      source: 'grammar',
      statement: 'Du pain means "some bread" (partitive).',
      answer: true,
      prompt: 'True or false?',
      explanation: 'Du = de + le (partitive masculine).',
    },
    {
      id: 'c3-x-conj1',
      type: 'conjugation',
      category: 'vouloir',
      source: 'grammar',
      verb: 'vouloir',
      tense: 'Présent',
      pronoun: 'je',
      answers: ['veux'],
      prompt: 'Conjugate vouloir (Présent): je ___',
      explanation: 'Je veux.',
    },
    {
      id: 'c3-x-register1',
      type: 'register',
      category: 'tu-vous',
      source: 'grammar',
      situation: 'Ordering from a waiter you do not know.',
      options: ['Je veux un café.', 'Je voudrais un café, s\'il vous plaît.', 'Donne-moi un café.'],
      answer: 1,
      prompt: 'Most polite order?',
      explanation: 'Je voudrais… s\'il vous plaît is courteous.',
    },
    {
      id: 'c3-x-spot1',
      type: 'spot-error',
      category: 'ordering',
      source: 'grammar',
      sentence: 'Un café, sil vous plait.',
      words: ['Un', 'café,', 'sil', 'vous', 'plait.'],
      errorIndex: 2,
      prompt: 'Find the misspelled word.',
      explanation: 's\'il vous plaît — with apostrophe and circumflex on plaît.',
    },
    {
      id: 'c3-x-dialogue1',
      type: 'dialogue',
      category: 'conversation',
      source: 'dialogue',
      context: 'The waiter brings drinks and says « Voilà vos boissons. » You should say…',
      options: ['De rien.', 'Merci beaucoup !', 'L\'addition, s\'il vous plaît.'],
      answer: 1,
      prompt: 'Best response?',
      explanation: 'Thank the waiter when they serve you.',
    },
    {
      id: 'c3-x-reading1',
      type: 'mcq',
      category: 'café-vocab',
      source: 'grammar',
      options: ['à la terrasse', 'au comptoir seulement', 'à la maison'],
      answer: 0,
      prompt: 'Where do you sit outside at a café?',
      explanation: 'À la terrasse = on the terrace / patio.',
    },
    {
      id: 'c3-x-minimal1',
      type: 'minimal-pair',
      category: 'payer',
      source: 'grammar',
      options: ['Je paye l\'addition.', 'Je paie l\'addition.', 'Je payes l\'addition.'],
      answer: 1,
      prompt: 'Which spelling is standard?',
      explanation: 'Je paie (payer) — both paye/paie exist but paie is preferred in modern usage.',
    },
  ],
  '22222222-0000-0000-0000-000000000104': [
    {
      id: 'c4-x-cloze1',
      type: 'cloze',
      category: 'possessives',
      source: 'grammar',
      text: '___ mère s\'appelle Claire.',
      answers: ['Ma', 'ma'],
      prompt: 'Type the possessive (my — feminine).',
      explanation: 'Ma mère — feminine singular possessive.',
    },
    {
      id: 'c4-x-cloze2',
      type: 'cloze',
      category: 'family',
      source: 'grammar',
      text: 'J\'ai deux ___.',
      answers: ['frères', 'freres'],
      prompt: 'Type the word for "brothers".',
      explanation: 'Frère → frères in the plural.',
    },
    {
      id: 'c4-x-match1',
      type: 'match',
      category: 'family',
      source: 'grammar',
      left: ['père', 'sœur', 'cousin', 'grand-mère'],
      right: ['father', 'sister', 'cousin (m.)', 'grandmother'],
      pairs: [[0, 0], [1, 1], [2, 2], [3, 3]],
      prompt: 'Match family words.',
      explanation: 'Note œ in sœur.',
    },
    {
      id: 'c4-x-order1',
      type: 'order',
      category: 'family',
      source: 'grammar',
      words: ['frère', 'Mon', 's\'appelle', 'Lucas.'],
      answer: ['Mon', 'frère', 's\'appelle', 'Lucas.'],
      prompt: 'Build: My brother is called Lucas.',
      explanation: 'Mon frère s\'appelle Lucas.',
    },
    {
      id: 'c4-x-translate1',
      type: 'translate',
      category: 'family',
      source: 'grammar',
      direction: 'en-fr',
      answers: ['ma famille', 'Ma famille'],
      prompt: 'Translate: "my family"',
      explanation: 'Ma famille — famille is feminine.',
    },
    {
      id: 'c4-x-tf1',
      type: 'true-false',
      category: 'possessives',
      source: 'grammar',
      statement: 'Before a vowel, ma becomes mon (e.g. mon amie).',
      answer: true,
      prompt: 'True or false?',
      explanation: 'Possessives agree with the noun; mon is used before vowel sounds.',
    },
    {
      id: 'c4-x-conj1',
      type: 'conjugation',
      category: 'avoir-present',
      source: 'grammar',
      verb: 'avoir',
      tense: 'Présent',
      pronoun: 'ils',
      answers: ['ont'],
      prompt: 'Conjugate avoir: ils ___',
      explanation: 'Ils ont deux frères.',
    },
    {
      id: 'c4-x-register1',
      type: 'register',
      category: 'family',
      source: 'grammar',
      situation: 'Talking about your family with a new friend (tu).',
      options: ['Mes parents habitent à Lyon.', 'Vos parents habitent où ?', 'Leur famille est grande.'],
      answer: 0,
      prompt: 'Natural informal sentence about your own family?',
      explanation: 'Mes parents… with tu register between peers.',
    },
    {
      id: 'c4-x-spot1',
      type: 'spot-error',
      category: 'possessives',
      source: 'grammar',
      sentence: 'Mon sœur est grande.',
      words: ['Mon', 'sœur', 'est', 'grande.'],
      errorIndex: 0,
      prompt: 'Which word has the wrong agreement?',
      explanation: 'Ma sœur — sœur is feminine.',
    },
    {
      id: 'c4-x-dialogue1',
      type: 'dialogue',
      category: 'conversation',
      source: 'dialogue',
      context: 'Sophie asks about your family. You have one sister. You say…',
      options: ['J\'ai une sœur.', 'J\'ai un sœur.', 'Je suis une sœur.'],
      answer: 0,
      prompt: 'Choose the correct line.',
      explanation: 'Avoir + une sœur.',
    },
    {
      id: 'c4-x-reading1',
      type: 'mcq',
      category: 'family',
      source: 'grammar',
      options: ['les grands-parents', 'les boissons', 'les chiffres'],
      answer: 0,
      prompt: 'Which word means “grandparents”?',
      explanation: 'Les grands-parents = grandparents.',
    },
    {
      id: 'c4-x-minimal1',
      type: 'minimal-pair',
      category: 'possessives',
      source: 'grammar',
      options: ['Mes frères sont grands.', 'Ma frères sont grands.', 'Mon frères sont grands.'],
      answer: 0,
      prompt: 'Which plural possessive is correct?',
      explanation: 'Mes + plural noun.',
    },
  ],
}
