import type { GrammarRuleDocument } from '@/lib/rules/types'

export const PHASE1_RULE_DOCUMENTS: GrammarRuleDocument[] = [
 {
 id: '30000000-0000-0000-0000-000000000101',
 slug: 'questions-est-ce-que',
 title: "Questions with est-ce que",
 category: "Questions",
 summary: "Est-ce que turns a statement into a yes/no question without changing word order much. Wh-words ask for details: qui, où, quand, pourquoi, comment, combien.",
 full_explanation: "Est-ce que turns a statement into a yes/no question without changing word order much. Wh-words ask for details: qui, où, quand, pourquoi, comment, combien. ",
 examples: [
 { french: "Est-ce que tu habites à Paris ?", english: "Est-ce que tu habites à Paris ?" },
 { french: "Où habites-tu ?", english: "Où habites-tu ?" },
 { french: "Qui est-ce ?", english: "Qui est-ce ?" },
 { french: "Qu'est-ce que c'est ?", english: "Qu'est-ce que c'est ?" },
 { french: "Quand arrives-tu ?", english: "Quand arrives-tu ?" },
 { french: "Pourquoi ?", english: "Pourquoi ?" },
 { french: "Comment ça va ?", english: "Comment ça va ?" },
 { french: "Combien ça coûte ?", english: "Combien ça coûte ?" },
 ],
 unlockChapterIds: ['22222222-0000-0000-0000-000000000204'],
 linkedLessons: [{ chapterId: '22222222-0000-0000-0000-000000000204', lessonLabel: 'Phase I', title: "Questions with est-ce que" }],
 relatedRules: [
 { slug: 'subject-pronouns', label: "Subject pronouns" },
 ],
 masteryCategories: ["questions", "est-ce-que"],
 quickReference: {
 bullets: ["Est-ce que tu habites à Paris ?", "Où habites-tu ?", "Qui est-ce ?", "Qu'est-ce que c'est ?", "Quand arrives-tu ?", "Pourquoi ?"],
 table: {
 headers: ['Pattern', 'Example'],
 rows: [
 ['Core', 'See bullets'],
 ['Trap', 'Meanings before forms'],
 ['Review', 'Grammar + vocab only'],
 ],
 },
 },
 deepDive: {
 whyItMatters: "Est-ce que turns a statement into a yes/no question without changing word order much. Wh-words ask for details: qui, où, quand, pourquoi, comment, combien. This pattern appears constantly in real conversation and in Phase I checkpoints.",
 sections: [
 { heading: 'Core pattern', body: "Est-ce que turns a statement into a yes/no question without changing word order much. Wh-words ask for details: qui, où, quand, pourquoi, comment, combien. " },
 { heading: 'How to practice', body: "Produce each example without looking, then mix with earlier forms. " },
 { heading: 'Traps', body: "Do not translate word-for-word from English every time. Keep French chunks whole. Check gender and articles when a noun is involved. " },
 ],
 commonMistakes: [
 { wrong: 'Skipping meanings', right: 'Learn English glosses first', why: 'Theory First rule' },
 { wrong: 'Quiz plot memory', right: 'Quiz forms and vocabulary', why: 'Review is vocab + grammar only' },
 { wrong: 'One exposure only', right: 'Spiral in later lessons', why: 'Checkpoints reuse the pattern' },
 ],
 },
 examplesByGroup: [
 { heading: 'Model sentences', items: [
 { french: "Est-ce que tu habites à Paris ?", english: "Est-ce que tu habites à Paris ?" },
 { french: "Où habites-tu ?", english: "Où habites-tu ?" },
 { french: "Qui est-ce ?", english: "Qui est-ce ?" },
 { french: "Qu'est-ce que c'est ?", english: "Qu'est-ce que c'est ?" },
 { french: "Quand arrives-tu ?", english: "Quand arrives-tu ?" },
 { french: "Pourquoi ?", english: "Pourquoi ?" },
 { french: "Comment ça va ?", english: "Comment ça va ?" },
 { french: "Combien ça coûte ?", english: "Combien ça coûte ?" },
 ] },
 ],
 drills: [
 {
 id: 'questions-est-ce-que-d1',
 title: 'Pick the correct form',
 exercise: {
 id: 'questions-est-ce-que-d1e',
 category: "questions",
 prompt: 'Choose:',
 options: ["Est-ce que tu habites à Paris ?", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "Est-ce que tu habites à Paris ?",
 },
 },
 {
 id: 'questions-est-ce-que-d2',
 title: 'Pick again',
 exercise: {
 id: 'questions-est-ce-que-d2e',
 category: "questions",
 prompt: 'Choose:',
 options: ["Où habites-tu ?", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "Où habites-tu ?",
 },
 },
 ],
 },
 {
 id: '30000000-0000-0000-0000-000000000102',
 slug: 'reflexives-present',
 title: "Reflexive verbs (present)",
 category: "Verbs",
 summary: "Reflexive verbs use an object pronoun that matches the subject: me, te, se, nous, vous, se. Common morning verbs: se lever, se laver.",
 full_explanation: "Reflexive verbs use an object pronoun that matches the subject: me, te, se, nous, vous, se. Common morning verbs: se lever, se laver. ",
 examples: [
 { french: "Je me lève.", english: "Je me lève." },
 { french: "Tu te laves.", english: "Tu te laves." },
 { french: "Il se lave.", english: "Il se lave." },
 { french: "Nous nous levons.", english: "Nous nous levons." },
 { french: "Vous vous lavez.", english: "Vous vous lavez." },
 { french: "Elles se lèvent.", english: "Elles se lèvent." },
 { french: "Je me lève à sept heures.", english: "Je me lève à sept heures." },
 { french: "Tu te laves le matin.", english: "Tu te laves le matin." },
 ],
 unlockChapterIds: ['22222222-0000-0000-0000-000000000301'],
 linkedLessons: [{ chapterId: '22222222-0000-0000-0000-000000000301', lessonLabel: 'Phase I', title: "Reflexive verbs (present)" }],
 relatedRules: [
 { slug: 'er-present', label: "-ER present" },
 ],
 masteryCategories: ["reflexives", "se-lever"],
 quickReference: {
 bullets: ["Je me lève.", "Tu te laves.", "Il se lave.", "Nous nous levons.", "Vous vous lavez.", "Elles se lèvent."],
 table: {
 headers: ['Pattern', 'Example'],
 rows: [
 ['Core', 'See bullets'],
 ['Trap', 'Meanings before forms'],
 ['Review', 'Grammar + vocab only'],
 ],
 },
 },
 deepDive: {
 whyItMatters: "Reflexive verbs use an object pronoun that matches the subject: me, te, se, nous, vous, se. Common morning verbs: se lever, se laver. This pattern appears constantly in real conversation and in Phase I checkpoints.",
 sections: [
 { heading: 'Core pattern', body: "Reflexive verbs use an object pronoun that matches the subject: me, te, se, nous, vous, se. Common morning verbs: se lever, se laver. " },
 { heading: 'How to practice', body: "Produce each example without looking, then mix with earlier forms. " },
 { heading: 'Traps', body: "Do not translate word-for-word from English every time. Keep French chunks whole. Check gender and articles when a noun is involved. " },
 ],
 commonMistakes: [
 { wrong: 'Skipping meanings', right: 'Learn English glosses first', why: 'Theory First rule' },
 { wrong: 'Quiz plot memory', right: 'Quiz forms and vocabulary', why: 'Review is vocab + grammar only' },
 { wrong: 'One exposure only', right: 'Spiral in later lessons', why: 'Checkpoints reuse the pattern' },
 ],
 },
 examplesByGroup: [
 { heading: 'Model sentences', items: [
 { french: "Je me lève.", english: "Je me lève." },
 { french: "Tu te laves.", english: "Tu te laves." },
 { french: "Il se lave.", english: "Il se lave." },
 { french: "Nous nous levons.", english: "Nous nous levons." },
 { french: "Vous vous lavez.", english: "Vous vous lavez." },
 { french: "Elles se lèvent.", english: "Elles se lèvent." },
 { french: "Je me lève à sept heures.", english: "Je me lève à sept heures." },
 { french: "Tu te laves le matin.", english: "Tu te laves le matin." },
 ] },
 ],
 drills: [
 {
 id: 'reflexives-present-d1',
 title: 'Pick the correct form',
 exercise: {
 id: 'reflexives-present-d1e',
 category: "reflexives",
 prompt: 'Choose:',
 options: ["Je me lève.", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "Je me lève.",
 },
 },
 {
 id: 'reflexives-present-d2',
 title: 'Pick again',
 exercise: {
 id: 'reflexives-present-d2e',
 category: "reflexives",
 prompt: 'Choose:',
 options: ["Tu te laves.", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "Tu te laves.",
 },
 },
 ],
 },
 {
 id: '30000000-0000-0000-0000-000000000103',
 slug: 'clock-time',
 title: "Telling time",
 category: "Numbers & time",
 summary: "Ask Quelle heure est-il ? Answer with Il est + hour. Add et quart, et demie, or moins le quart. Midi and minuit replace douze heures in many contexts.",
 full_explanation: "Ask Quelle heure est-il ? Answer with Il est + hour. Add et quart, et demie, or moins le quart. Midi and minuit replace douze heures in many contexts. ",
 examples: [
 { french: "Il est trois heures.", english: "Il est trois heures." },
 { french: "Il est trois heures et demie.", english: "Il est trois heures et demie." },
 { french: "Il est trois heures et quart.", english: "Il est trois heures et quart." },
 { french: "Il est quatre heures moins le quart.", english: "Il est quatre heures moins le quart." },
 { french: "Il est midi.", english: "Il est midi." },
 { french: "Il est minuit.", english: "Il est minuit." },
 { french: "Quelle heure est-il ?", english: "Quelle heure est-il ?" },
 { french: "Il est déjà huit heures.", english: "Il est déjà huit heures." },
 ],
 unlockChapterIds: ['22222222-0000-0000-0000-000000000303'],
 linkedLessons: [{ chapterId: '22222222-0000-0000-0000-000000000303', lessonLabel: 'Phase I', title: "Telling time" }],
 relatedRules: [
 { slug: 'numbers-and-age', label: "Numbers & age" },
 ],
 masteryCategories: ["time", "clock"],
 quickReference: {
 bullets: ["Il est trois heures.", "Il est trois heures et demie.", "Il est trois heures et quart.", "Il est quatre heures moins le quart.", "Il est midi.", "Il est minuit."],
 table: {
 headers: ['Pattern', 'Example'],
 rows: [
 ['Core', 'See bullets'],
 ['Trap', 'Meanings before forms'],
 ['Review', 'Grammar + vocab only'],
 ],
 },
 },
 deepDive: {
 whyItMatters: "Ask Quelle heure est-il ? Answer with Il est + hour. Add et quart, et demie, or moins le quart. Midi and minuit replace douze heures in many contexts. This pattern appears constantly in real conversation and in Phase I checkpoints.",
 sections: [
 { heading: 'Core pattern', body: "Ask Quelle heure est-il ? Answer with Il est + hour. Add et quart, et demie, or moins le quart. Midi and minuit replace douze heures in many contexts. " },
 { heading: 'How to practice', body: "Produce each example without looking, then mix with earlier forms. " },
 { heading: 'Traps', body: "Do not translate word-for-word from English every time. Keep French chunks whole. Check gender and articles when a noun is involved. " },
 ],
 commonMistakes: [
 { wrong: 'Skipping meanings', right: 'Learn English glosses first', why: 'Theory First rule' },
 { wrong: 'Quiz plot memory', right: 'Quiz forms and vocabulary', why: 'Review is vocab + grammar only' },
 { wrong: 'One exposure only', right: 'Spiral in later lessons', why: 'Checkpoints reuse the pattern' },
 ],
 },
 examplesByGroup: [
 { heading: 'Model sentences', items: [
 { french: "Il est trois heures.", english: "Il est trois heures." },
 { french: "Il est trois heures et demie.", english: "Il est trois heures et demie." },
 { french: "Il est trois heures et quart.", english: "Il est trois heures et quart." },
 { french: "Il est quatre heures moins le quart.", english: "Il est quatre heures moins le quart." },
 { french: "Il est midi.", english: "Il est midi." },
 { french: "Il est minuit.", english: "Il est minuit." },
 { french: "Quelle heure est-il ?", english: "Quelle heure est-il ?" },
 { french: "Il est déjà huit heures.", english: "Il est déjà huit heures." },
 ] },
 ],
 drills: [
 {
 id: 'clock-time-d1',
 title: 'Pick the correct form',
 exercise: {
 id: 'clock-time-d1e',
 category: "time",
 prompt: 'Choose:',
 options: ["Il est trois heures.", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "Il est trois heures.",
 },
 },
 {
 id: 'clock-time-d2',
 title: 'Pick again',
 exercise: {
 id: 'clock-time-d2e',
 category: "time",
 prompt: 'Choose:',
 options: ["Il est trois heures et demie.", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "Il est trois heures et demie.",
 },
 },
 ],
 },
 {
 id: '30000000-0000-0000-0000-000000000104',
 slug: 'il-y-a',
 title: "Il y a (there is / there are)",
 category: "Sentence builders",
 summary: "Il y a introduces what exists in a place. Use un/une/des before countable nouns. Negation often becomes il n’y a pas de…",
 full_explanation: "Il y a introduces what exists in a place. Use un/une/des before countable nouns. Negation often becomes il n’y a pas de… ",
 examples: [
 { french: "Il y a un parc.", english: "Il y a un parc." },
 { french: "Il y a une pharmacie.", english: "Il y a une pharmacie." },
 { french: "Il y a des magasins.", english: "Il y a des magasins." },
 { french: "Il y a une banque.", english: "Il y a une banque." },
 { french: "Il n’y a pas de métro.", english: "Il n’y a pas de métro." },
 { french: "Dans la rue, il y a un café.", english: "Dans la rue, il y a un café." },
 { french: "Il y a un hôpital près d’ici.", english: "Il y a un hôpital près d’ici." },
 { french: "Il y a deux chambres.", english: "Il y a deux chambres." },
 ],
 unlockChapterIds: ['22222222-0000-0000-0000-000000000401'],
 linkedLessons: [{ chapterId: '22222222-0000-0000-0000-000000000401', lessonLabel: 'Phase I', title: "Il y a (there is / there are)" }],
 relatedRules: [
 { slug: 'articles-partitives', label: "Articles & partitives" },
 ],
 masteryCategories: ["il-y-a"],
 quickReference: {
 bullets: ["Il y a un parc.", "Il y a une pharmacie.", "Il y a des magasins.", "Il y a une banque.", "Il n’y a pas de métro.", "Dans la rue, il y a un café."],
 table: {
 headers: ['Pattern', 'Example'],
 rows: [
 ['Core', 'See bullets'],
 ['Trap', 'Meanings before forms'],
 ['Review', 'Grammar + vocab only'],
 ],
 },
 },
 deepDive: {
 whyItMatters: "Il y a introduces what exists in a place. Use un/une/des before countable nouns. Negation often becomes il n’y a pas de… This pattern appears constantly in real conversation and in Phase I checkpoints.",
 sections: [
 { heading: 'Core pattern', body: "Il y a introduces what exists in a place. Use un/une/des before countable nouns. Negation often becomes il n’y a pas de… " },
 { heading: 'How to practice', body: "Produce each example without looking, then mix with earlier forms. " },
 { heading: 'Traps', body: "Do not translate word-for-word from English every time. Keep French chunks whole. Check gender and articles when a noun is involved. " },
 ],
 commonMistakes: [
 { wrong: 'Skipping meanings', right: 'Learn English glosses first', why: 'Theory First rule' },
 { wrong: 'Quiz plot memory', right: 'Quiz forms and vocabulary', why: 'Review is vocab + grammar only' },
 { wrong: 'One exposure only', right: 'Spiral in later lessons', why: 'Checkpoints reuse the pattern' },
 ],
 },
 examplesByGroup: [
 { heading: 'Model sentences', items: [
 { french: "Il y a un parc.", english: "Il y a un parc." },
 { french: "Il y a une pharmacie.", english: "Il y a une pharmacie." },
 { french: "Il y a des magasins.", english: "Il y a des magasins." },
 { french: "Il y a une banque.", english: "Il y a une banque." },
 { french: "Il n’y a pas de métro.", english: "Il n’y a pas de métro." },
 { french: "Dans la rue, il y a un café.", english: "Dans la rue, il y a un café." },
 { french: "Il y a un hôpital près d’ici.", english: "Il y a un hôpital près d’ici." },
 { french: "Il y a deux chambres.", english: "Il y a deux chambres." },
 ] },
 ],
 drills: [
 {
 id: 'il-y-a-d1',
 title: 'Pick the correct form',
 exercise: {
 id: 'il-y-a-d1e',
 category: "il-y-a",
 prompt: 'Choose:',
 options: ["Il y a un parc.", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "Il y a un parc.",
 },
 },
 {
 id: 'il-y-a-d2',
 title: 'Pick again',
 exercise: {
 id: 'il-y-a-d2e',
 category: "il-y-a",
 prompt: 'Choose:',
 options: ["Il y a une pharmacie.", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "Il y a une pharmacie.",
 },
 },
 ],
 },
 {
 id: '30000000-0000-0000-0000-000000000105',
 slug: 'aller-present',
 title: "Aller (to go) present",
 category: "Verbs",
 summary: "Aller is irregular: je vais, tu vas, il/elle/on va, nous allons, vous allez, ils/elles vont. Transport often uses en (en métro, en bus) or à pied.",
 full_explanation: "Aller is irregular: je vais, tu vas, il/elle/on va, nous allons, vous allez, ils/elles vont. Transport often uses en (en métro, en bus) or à pied. ",
 examples: [
 { french: "Je vais en métro.", english: "Je vais en métro." },
 { french: "Tu vas à pied.", english: "Tu vas à pied." },
 { french: "Il va au travail.", english: "Il va au travail." },
 { french: "Nous allons en bus.", english: "Nous allons en bus." },
 { french: "Vous allez à la gare.", english: "Vous allez à la gare." },
 { french: "Ils vont en train.", english: "Ils vont en train." },
 { french: "Je vais au bureau.", english: "Je vais au bureau." },
 { french: "Tu vas à l’école.", english: "Tu vas à l’école." },
 ],
 unlockChapterIds: ['22222222-0000-0000-0000-000000000402'],
 linkedLessons: [{ chapterId: '22222222-0000-0000-0000-000000000402', lessonLabel: 'Phase I', title: "Aller (to go) present" }],
 relatedRules: [
 { slug: 'er-present', label: "-ER present" },
 ],
 masteryCategories: ["aller"],
 quickReference: {
 bullets: ["Je vais en métro.", "Tu vas à pied.", "Il va au travail.", "Nous allons en bus.", "Vous allez à la gare.", "Ils vont en train."],
 table: {
 headers: ['Pattern', 'Example'],
 rows: [
 ['Core', 'See bullets'],
 ['Trap', 'Meanings before forms'],
 ['Review', 'Grammar + vocab only'],
 ],
 },
 },
 deepDive: {
 whyItMatters: "Aller is irregular: je vais, tu vas, il/elle/on va, nous allons, vous allez, ils/elles vont. Transport often uses en (en métro, en bus) or à pied. This pattern appears constantly in real conversation and in Phase I checkpoints.",
 sections: [
 { heading: 'Core pattern', body: "Aller is irregular: je vais, tu vas, il/elle/on va, nous allons, vous allez, ils/elles vont. Transport often uses en (en métro, en bus) or à pied. " },
 { heading: 'How to practice', body: "Produce each example without looking, then mix with earlier forms. " },
 { heading: 'Traps', body: "Do not translate word-for-word from English every time. Keep French chunks whole. Check gender and articles when a noun is involved. " },
 ],
 commonMistakes: [
 { wrong: 'Skipping meanings', right: 'Learn English glosses first', why: 'Theory First rule' },
 { wrong: 'Quiz plot memory', right: 'Quiz forms and vocabulary', why: 'Review is vocab + grammar only' },
 { wrong: 'One exposure only', right: 'Spiral in later lessons', why: 'Checkpoints reuse the pattern' },
 ],
 },
 examplesByGroup: [
 { heading: 'Model sentences', items: [
 { french: "Je vais en métro.", english: "Je vais en métro." },
 { french: "Tu vas à pied.", english: "Tu vas à pied." },
 { french: "Il va au travail.", english: "Il va au travail." },
 { french: "Nous allons en bus.", english: "Nous allons en bus." },
 { french: "Vous allez à la gare.", english: "Vous allez à la gare." },
 { french: "Ils vont en train.", english: "Ils vont en train." },
 { french: "Je vais au bureau.", english: "Je vais au bureau." },
 { french: "Tu vas à l’école.", english: "Tu vas à l’école." },
 ] },
 ],
 drills: [
 {
 id: 'aller-present-d1',
 title: 'Pick the correct form',
 exercise: {
 id: 'aller-present-d1e',
 category: "aller",
 prompt: 'Choose:',
 options: ["Je vais en métro.", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "Je vais en métro.",
 },
 },
 {
 id: 'aller-present-d2',
 title: 'Pick again',
 exercise: {
 id: 'aller-present-d2e',
 category: "aller",
 prompt: 'Choose:',
 options: ["Tu vas à pied.", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "Tu vas à pied.",
 },
 },
 ],
 },
 {
 id: '30000000-0000-0000-0000-000000000106',
 slug: 'adjective-agreement',
 title: "Adjective agreement",
 category: "Adjectives",
 summary: "French adjectives agree in gender and number with the noun they describe. Many add -e for feminine and -s for plural; some have special forms (blanc/blanche, beau/belle).",
 full_explanation: "French adjectives agree in gender and number with the noun they describe. Many add -e for feminine and -s for plural; some have special forms (blanc/blanche, beau/belle). ",
 examples: [
 { french: "un pull bleu", english: "un pull bleu" },
 { french: "une robe bleue", english: "une robe bleue" },
 { french: "un pantalon noir", english: "un pantalon noir" },
 { french: "une veste noire", english: "une veste noire" },
 { french: "des chaussures blanches", english: "des chaussures blanches" },
 { french: "un pull vert", english: "un pull vert" },
 { french: "une veste verte", english: "une veste verte" },
 { french: "Elle est française.", english: "Elle est française." },
 ],
 unlockChapterIds: ['22222222-0000-0000-0000-000000000502'],
 linkedLessons: [{ chapterId: '22222222-0000-0000-0000-000000000502', lessonLabel: 'Phase I', title: "Adjective agreement" }],
 relatedRules: [
 { slug: 'etre-present', label: "Être present" },
 ],
 masteryCategories: ["adjectives", "agreement"],
 quickReference: {
 bullets: ["un pull bleu", "une robe bleue", "un pantalon noir", "une veste noire", "des chaussures blanches", "un pull vert"],
 table: {
 headers: ['Pattern', 'Example'],
 rows: [
 ['Core', 'See bullets'],
 ['Trap', 'Meanings before forms'],
 ['Review', 'Grammar + vocab only'],
 ],
 },
 },
 deepDive: {
 whyItMatters: "French adjectives agree in gender and number with the noun they describe. Many add -e for feminine and -s for plural; some have special forms (blanc/blanche, beau/belle). This pattern appears constantly in real conversation and in Phase I checkpoints.",
 sections: [
 { heading: 'Core pattern', body: "French adjectives agree in gender and number with the noun they describe. Many add -e for feminine and -s for plural; some have special forms (blanc/blanche, beau/belle). " },
 { heading: 'How to practice', body: "Produce each example without looking, then mix with earlier forms. " },
 { heading: 'Traps', body: "Do not translate word-for-word from English every time. Keep French chunks whole. Check gender and articles when a noun is involved. " },
 ],
 commonMistakes: [
 { wrong: 'Skipping meanings', right: 'Learn English glosses first', why: 'Theory First rule' },
 { wrong: 'Quiz plot memory', right: 'Quiz forms and vocabulary', why: 'Review is vocab + grammar only' },
 { wrong: 'One exposure only', right: 'Spiral in later lessons', why: 'Checkpoints reuse the pattern' },
 ],
 },
 examplesByGroup: [
 { heading: 'Model sentences', items: [
 { french: "un pull bleu", english: "un pull bleu" },
 { french: "une robe bleue", english: "une robe bleue" },
 { french: "un pantalon noir", english: "un pantalon noir" },
 { french: "une veste noire", english: "une veste noire" },
 { french: "des chaussures blanches", english: "des chaussures blanches" },
 { french: "un pull vert", english: "un pull vert" },
 { french: "une veste verte", english: "une veste verte" },
 { french: "Elle est française.", english: "Elle est française." },
 ] },
 ],
 drills: [
 {
 id: 'adjective-agreement-d1',
 title: 'Pick the correct form',
 exercise: {
 id: 'adjective-agreement-d1e',
 category: "adjectives",
 prompt: 'Choose:',
 options: ["un pull bleu", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "un pull bleu",
 },
 },
 {
 id: 'adjective-agreement-d2',
 title: 'Pick again',
 exercise: {
 id: 'adjective-agreement-d2e',
 category: "adjectives",
 prompt: 'Choose:',
 options: ["une robe bleue", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "une robe bleue",
 },
 },
 ],
 },
 {
 id: '30000000-0000-0000-0000-000000000107',
 slug: 'negation-ne-pas',
 title: "Negation: ne…pas / jamais",
 category: "Sentence builders",
 summary: "Standard negation wraps the conjugated verb: ne + verb + pas. Use n’ before a vowel sound. Jamais means never. Ne…que means only.",
 full_explanation: "Standard negation wraps the conjugated verb: ne + verb + pas. Use n’ before a vowel sound. Jamais means never. Ne…que means only. ",
 examples: [
 { french: "Je ne suis pas anglais.", english: "Je ne suis pas anglais." },
 { french: "Je n’aime pas le thé.", english: "Je n’aime pas le thé." },
 { french: "Je n’habite pas à Lyon.", english: "Je n’habite pas à Lyon." },
 { french: "Je ne fume jamais.", english: "Je ne fume jamais." },
 { french: "Je n’ai que de l’eau.", english: "Je n’ai que de l’eau." },
 { french: "Tu n’es pas prêt.", english: "Tu n’es pas prêt." },
 { french: "Il ne part pas.", english: "Il ne part pas." },
 { french: "Nous ne mangeons pas de viande.", english: "Nous ne mangeons pas de viande." },
 ],
 unlockChapterIds: ['22222222-0000-0000-0000-000000000505'],
 linkedLessons: [{ chapterId: '22222222-0000-0000-0000-000000000505', lessonLabel: 'Phase I', title: "Negation: ne…pas / jamais" }],
 relatedRules: [
 { slug: 'etre-present', label: "Être present" },
 ],
 masteryCategories: ["negation", "ne-pas", "jamais"],
 quickReference: {
 bullets: ["Je ne suis pas anglais.", "Je n’aime pas le thé.", "Je n’habite pas à Lyon.", "Je ne fume jamais.", "Je n’ai que de l’eau.", "Tu n’es pas prêt."],
 table: {
 headers: ['Pattern', 'Example'],
 rows: [
 ['Core', 'See bullets'],
 ['Trap', 'Meanings before forms'],
 ['Review', 'Grammar + vocab only'],
 ],
 },
 },
 deepDive: {
 whyItMatters: "Standard negation wraps the conjugated verb: ne + verb + pas. Use n’ before a vowel sound. Jamais means never. Ne…que means only. This pattern appears constantly in real conversation and in Phase I checkpoints.",
 sections: [
 { heading: 'Core pattern', body: "Standard negation wraps the conjugated verb: ne + verb + pas. Use n’ before a vowel sound. Jamais means never. Ne…que means only. " },
 { heading: 'How to practice', body: "Produce each example without looking, then mix with earlier forms. " },
 { heading: 'Traps', body: "Do not translate word-for-word from English every time. Keep French chunks whole. Check gender and articles when a noun is involved. " },
 ],
 commonMistakes: [
 { wrong: 'Skipping meanings', right: 'Learn English glosses first', why: 'Theory First rule' },
 { wrong: 'Quiz plot memory', right: 'Quiz forms and vocabulary', why: 'Review is vocab + grammar only' },
 { wrong: 'One exposure only', right: 'Spiral in later lessons', why: 'Checkpoints reuse the pattern' },
 ],
 },
 examplesByGroup: [
 { heading: 'Model sentences', items: [
 { french: "Je ne suis pas anglais.", english: "Je ne suis pas anglais." },
 { french: "Je n’aime pas le thé.", english: "Je n’aime pas le thé." },
 { french: "Je n’habite pas à Lyon.", english: "Je n’habite pas à Lyon." },
 { french: "Je ne fume jamais.", english: "Je ne fume jamais." },
 { french: "Je n’ai que de l’eau.", english: "Je n’ai que de l’eau." },
 { french: "Tu n’es pas prêt.", english: "Tu n’es pas prêt." },
 { french: "Il ne part pas.", english: "Il ne part pas." },
 { french: "Nous ne mangeons pas de viande.", english: "Nous ne mangeons pas de viande." },
 ] },
 ],
 drills: [
 {
 id: 'negation-ne-pas-d1',
 title: 'Pick the correct form',
 exercise: {
 id: 'negation-ne-pas-d1e',
 category: "negation",
 prompt: 'Choose:',
 options: ["Je ne suis pas anglais.", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "Je ne suis pas anglais.",
 },
 },
 {
 id: 'negation-ne-pas-d2',
 title: 'Pick again',
 exercise: {
 id: 'negation-ne-pas-d2e',
 category: "negation",
 prompt: 'Choose:',
 options: ["Je n’aime pas le thé.", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "Je n’aime pas le thé.",
 },
 },
 ],
 },
 {
 id: '30000000-0000-0000-0000-000000000108',
 slug: 'demonstratives',
 title: "Demonstratives & c’est / ce sont",
 category: "Articles",
 summary: "Ce/cet/cette/ces point to specific nouns. C’est introduces a singular identification; ce sont introduces a plural. Keep the Module 1 trap: c’est + name vs il/elle est + adjective.",
 full_explanation: "Ce/cet/cette/ces point to specific nouns. C’est introduces a singular identification; ce sont introduces a plural. Keep the Module 1 trap: c’est + name vs il/elle est + adjective. ",
 examples: [
 { french: "C’est un livre.", english: "C’est un livre." },
 { french: "Ce sont des stylos.", english: "Ce sont des stylos." },
 { french: "C’est Marie.", english: "C’est Marie." },
 { french: "Elle est française.", english: "Elle est française." },
 { french: "Cette table", english: "Cette table" },
 { french: "Cet ami", english: "Cet ami" },
 { french: "Ces fruits", english: "Ces fruits" },
 { french: "Qu’est-ce que c’est ?", english: "Qu’est-ce que c’est ?" },
 ],
 unlockChapterIds: ['22222222-0000-0000-0000-000000000202'],
 linkedLessons: [{ chapterId: '22222222-0000-0000-0000-000000000202', lessonLabel: 'Phase I', title: "Demonstratives & c’est / ce sont" }],
 relatedRules: [
 { slug: 'cest-versus-il-est', label: "C'est vs il/elle est" },
 ],
 masteryCategories: ["demonstratives", "cest-versus-il-est"],
 quickReference: {
 bullets: ["C’est un livre.", "Ce sont des stylos.", "C’est Marie.", "Elle est française.", "Cette table", "Cet ami"],
 table: {
 headers: ['Pattern', 'Example'],
 rows: [
 ['Core', 'See bullets'],
 ['Trap', 'Meanings before forms'],
 ['Review', 'Grammar + vocab only'],
 ],
 },
 },
 deepDive: {
 whyItMatters: "Ce/cet/cette/ces point to specific nouns. C’est introduces a singular identification; ce sont introduces a plural. Keep the Module 1 trap: c’est + name vs il/elle est + adjective. This pattern appears constantly in real conversation and in Phase I checkpoints.",
 sections: [
 { heading: 'Core pattern', body: "Ce/cet/cette/ces point to specific nouns. C’est introduces a singular identification; ce sont introduces a plural. Keep the Module 1 trap: c’est + name vs il/elle est + adjective. " },
 { heading: 'How to practice', body: "Produce each example without looking, then mix with earlier forms. " },
 { heading: 'Traps', body: "Do not translate word-for-word from English every time. Keep French chunks whole. Check gender and articles when a noun is involved. " },
 ],
 commonMistakes: [
 { wrong: 'Skipping meanings', right: 'Learn English glosses first', why: 'Theory First rule' },
 { wrong: 'Quiz plot memory', right: 'Quiz forms and vocabulary', why: 'Review is vocab + grammar only' },
 { wrong: 'One exposure only', right: 'Spiral in later lessons', why: 'Checkpoints reuse the pattern' },
 ],
 },
 examplesByGroup: [
 { heading: 'Model sentences', items: [
 { french: "C’est un livre.", english: "C’est un livre." },
 { french: "Ce sont des stylos.", english: "Ce sont des stylos." },
 { french: "C’est Marie.", english: "C’est Marie." },
 { french: "Elle est française.", english: "Elle est française." },
 { french: "Cette table", english: "Cette table" },
 { french: "Cet ami", english: "Cet ami" },
 { french: "Ces fruits", english: "Ces fruits" },
 { french: "Qu’est-ce que c’est ?", english: "Qu’est-ce que c’est ?" },
 ] },
 ],
 drills: [
 {
 id: 'demonstratives-d1',
 title: 'Pick the correct form',
 exercise: {
 id: 'demonstratives-d1e',
 category: "demonstratives",
 prompt: 'Choose:',
 options: ["C’est un livre.", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "C’est un livre.",
 },
 },
 {
 id: 'demonstratives-d2',
 title: 'Pick again',
 exercise: {
 id: 'demonstratives-d2e',
 category: "demonstratives",
 prompt: 'Choose:',
 options: ["Ce sont des stylos.", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "Ce sont des stylos.",
 },
 },
 ],
 },
 {
 id: '30000000-0000-0000-0000-000000000109',
 slug: 'habiter-prepositions',
 title: "Habiter: à / en / au / aux",
 category: "Prepositions",
 summary: "Habiter needs the right place preposition: à + city, en + feminine country, au + masculine country, aux + plural country names.",
 full_explanation: "Habiter needs the right place preposition: à + city, en + feminine country, au + masculine country, aux + plural country names. Learn the place first, then lock the preposition. Cities almost always take à: j’habite à Paris, à Lyon, à Montréal. Feminine country names often take en: en France, en Belgique, en Suisse. Masculine country names often take au: au Canada, au Japon, au Maroc. Plural country names take aux: aux États-Unis, aux Pays-Bas. When you are unsure, ask: is this a city, a feminine country, a masculine country, or a plural name? Say each pair aloud. Do not invent English-style “in Paris” calques with en + city. Keep chunks whole: j’habite à + city. Mix with être and greetings so the pattern does not sit alone. Short daily review beats one long cram session for these prepositions.",
 examples: [
 { french: "J’habite à Paris.", english: "J’habite à Paris." },
 { french: "J’habite à Lyon.", english: "J’habite à Lyon." },
 { french: "J’habite en France.", english: "J’habite en France." },
 { french: "J’habite en Belgique.", english: "J’habite en Belgique." },
 { french: "J’habite au Canada.", english: "J’habite au Canada." },
 { french: "J’habite aux États-Unis.", english: "J’habite aux États-Unis." },
 { french: "Où habites-tu ?", english: "Où habites-tu ?" },
 { french: "Nous habitons en Suisse.", english: "Nous habitons en Suisse." },
 ],
 unlockChapterIds: ['22222222-0000-0000-0000-000000000201'],
 linkedLessons: [{ chapterId: '22222222-0000-0000-0000-000000000201', lessonLabel: 'Phase I', title: "Habiter: à / en / au / aux" }],
 relatedRules: [
 { slug: 'etre-present', label: "Être present" },
 ],
 masteryCategories: ["habiter", "prepositions"],
 quickReference: {
 bullets: ["J’habite à Paris.", "J’habite à Lyon.", "J’habite en France.", "J’habite en Belgique.", "J’habite au Canada.", "J’habite aux États-Unis."],
 table: {
 headers: ['Pattern', 'Example'],
 rows: [
 ['Core', 'See bullets'],
 ['Trap', 'Meanings before forms'],
 ['Review', 'Grammar + vocab only'],
 ],
 },
 },
 deepDive: {
 whyItMatters: "Habiter needs the right place preposition: à + city, en + feminine country, au + masculine country, aux + plural country names. This pattern appears constantly in real conversation and in Phase I checkpoints.",
 sections: [
 { heading: 'Core pattern', body: "Habiter needs the right place preposition: à + city, en + feminine country, au + masculine country, aux + plural country names. " },
 { heading: 'How to practice', body: "Produce each example without looking, then mix with earlier forms. " },
 { heading: 'Traps', body: "Do not translate word-for-word from English every time. Keep French chunks whole. Check gender and articles when a noun is involved. " },
 ],
 commonMistakes: [
 { wrong: 'Skipping meanings', right: 'Learn English glosses first', why: 'Theory First rule' },
 { wrong: 'Quiz plot memory', right: 'Quiz forms and vocabulary', why: 'Review is vocab + grammar only' },
 { wrong: 'One exposure only', right: 'Spiral in later lessons', why: 'Checkpoints reuse the pattern' },
 ],
 },
 examplesByGroup: [
 { heading: 'Model sentences', items: [
 { french: "J’habite à Paris.", english: "J’habite à Paris." },
 { french: "J’habite à Lyon.", english: "J’habite à Lyon." },
 { french: "J’habite en France.", english: "J’habite en France." },
 { french: "J’habite en Belgique.", english: "J’habite en Belgique." },
 { french: "J’habite au Canada.", english: "J’habite au Canada." },
 { french: "J’habite aux États-Unis.", english: "J’habite aux États-Unis." },
 { french: "Où habites-tu ?", english: "Où habites-tu ?" },
 { french: "Nous habitons en Suisse.", english: "Nous habitons en Suisse." },
 ] },
 ],
 drills: [
 {
 id: 'habiter-prepositions-d1',
 title: 'Pick the correct form',
 exercise: {
 id: 'habiter-prepositions-d1e',
 category: "habiter",
 prompt: 'Choose:',
 options: ["J’habite à Paris.", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "J’habite à Paris.",
 },
 },
 {
 id: 'habiter-prepositions-d2',
 title: 'Pick again',
 exercise: {
 id: 'habiter-prepositions-d2e',
 category: "habiter",
 prompt: 'Choose:',
 options: ["J’habite à Lyon.", 'Je suis Paris.', "C'est française."],
 answer: 0,
 explanation: "J’habite à Lyon.",
 },
 },
 ],
 },
]

