import type { VocabularyWord } from '@/lib/course'

/** Remaining high-frequency reading/dialogue surfaces for near-zero tap miss. */
function v(
  n: number,
  word: string,
  base_translation: string,
  part_of_speech: string,
  gender: 'masculine' | 'feminine' | null = null,
): VocabularyWord {
  const id = `10000000-0000-0000-0000-00000000${String(900 + n).padStart(4, '0')}`
  return {
    id,
    word,
    base_translation,
    meanings: [base_translation],
    example: { french: word, english: base_translation },
    part_of_speech,
    gender,
    register: 'Courant',
    ipa_pronunciation: null,
    is_idiom: part_of_speech === 'phrase',
    is_slang: false,
    idiom_explanation: null,
  }
}

const LETTERS: VocabularyWord[] = 'abcdefghijklmnopqrstuvwxyz'.split('').flatMap((ch, i) => [
  v(300 + i, ch, `the letter ${ch}`, 'noun', 'masculine'),
  v(330 + i, ch.toUpperCase(), `the letter ${ch.toUpperCase()}`, 'noun', 'masculine'),
])

export const TAP_FILL_VOCABULARY: VocabularyWord[] = [
  ...LETTERS,
  v(1, 'ok', 'OK / alright', 'interjection'),
  v(2, 'cool', 'cool', 'adjective'),
  v(3, 'ciao', 'bye (informal)', 'interjection'),
  v(4, 'bravo', 'well done', 'interjection'),
  v(5, 'envoyer', 'to send', 'verb'),
  v(6, 'aider', 'to help', 'verb'),
  v(7, 'fatigué', 'tired', 'adjective'),
  v(8, 'aux', 'to the / at the (à + les)', 'preposition'),
  v(9, 'rien', 'nothing', 'pronoun'),
  v(10, 'grave', 'grave / serious / grave accent', 'adjective'),
  v(11, 'vendeur', 'salesperson (m.)', 'noun', 'masculine'),
  v(12, 'vendeuse', 'salesperson (f.)', 'noun', 'feminine'),
  v(13, 'gentil', 'kind / nice', 'adjective'),
  v(14, 'gentille', 'kind / nice (f.)', 'adjective'),
  v(15, 'fumer', 'to smoke', 'verb'),
  v(16, 'mairie', 'town hall', 'noun', 'feminine'),
  v(17, 'hôpital', 'hospital', 'noun', 'masculine'),
  v(18, 'quartier', 'neighborhood', 'noun', 'masculine'),
  v(19, 'bleu', 'blue', 'adjective'),
  v(20, 'bleue', 'blue (f.)', 'adjective'),
  v(21, 'fois', 'time (occurrence)', 'noun', 'feminine'),
  v(22, 'automne', 'autumn', 'noun', 'masculine'),
  v(23, 'faux', 'false / fake', 'adjective'),
  v(24, 'silencieux', 'silent', 'adjective'),
  v(25, 'silencieuses', 'silent (f. pl.)', 'adjective'),
  v(26, 'liaison', 'liaison (linking sound)', 'noun', 'feminine'),
  v(27, 'état', 'state', 'noun', 'masculine'),
  v(28, 'retard', 'delay / lateness', 'noun', 'masculine'),
  v(29, 'weekend', 'weekend', 'noun', 'masculine'),
  v(30, 'ici', 'here', 'adverb'),
  v(31, 'perdre', 'to lose', 'verb'),
  v(32, 'perdu', 'lost', 'adjective'),
  v(33, 'kilo', 'kilo', 'noun', 'masculine'),
  v(34, 'tenue', 'outfit / holding', 'noun', 'feminine'),
  v(35, 'appétit', 'appetite', 'noun', 'masculine'),
  v(36, 'direct', 'direct', 'adjective'),
  v(37, 'indirect', 'indirect', 'adjective'),
  v(38, 'object', 'object (grammar)', 'noun', 'masculine'),
  v(39, 'présentation', 'presentation', 'noun', 'feminine'),
  v(40, 'muet', 'silent (letter)', 'adjective'),
  v(41, 'vrai', 'true', 'adjective'),
  v(42, 'maintenant', 'now', 'adverb'),
  v(43, 'assez', 'enough', 'adverb'),
  v(44, 'libre', 'free', 'adjective'),
  v(45, 'désolé', 'sorry', 'adjective'),
  v(46, 'noir', 'black', 'adjective'),
  v(47, 'noire', 'black (f.)', 'adjective'),
  v(48, 'pantalon', 'pants', 'noun', 'masculine'),
  v(49, 'veste', 'jacket', 'noun', 'feminine'),
  v(50, 'cinéma', 'cinema', 'noun', 'masculine'),
  v(51, 'lentement', 'slowly', 'adverb'),
  v(52, 'précision', 'precision', 'noun', 'feminine'),
  v(53, 'éviter', 'to avoid', 'verb'),
  v(54, 'garder', 'to keep', 'verb'),
  v(55, 'aigu', 'acute (accent)', 'adjective'),
  v(56, 'finales', 'final (f. pl.)', 'adjective'),
  v(57, 'matinée', 'morning (duration)', 'noun', 'feminine'),
  v(58, "qu'est-ce", 'what is it (start of question)', 'phrase'),
  v(59, "qu'est-ce que", 'what (question phrase)', 'phrase'),
  v(60, 'francophone', 'French-speaking', 'adjective'),
  v(61, 'passive', 'passive (voice)', 'adjective'),
  v(62, 'ID', 'ID', 'noun', 'masculine'),
  v(63, 'PP', 'passé composé (label)', 'noun', 'masculine'),
  v(64, 'II', 'II (phase label)', 'noun', 'masculine'),
  v(65, 'DR', 'DR (label)', 'noun', 'masculine'),
  v(66, 'è', 'è (letter with grave)', 'noun', 'masculine'),
  v(67, 'é', 'é (letter with acute)', 'noun', 'masculine'),
  v(68, 'ç', 'ç (c cedilla)', 'noun', 'masculine'),
  v(69, 'ê', 'ê (letter with circumflex)', 'noun', 'masculine'),
  v(70, 'wh', 'wh (sound label)', 'noun', 'masculine'),
  // High-frequency misses from tap audit
  v(71, 'savoir', 'to know', 'verb'),
  v(72, 'premier', 'first', 'adjective'),
  v(73, 'première', 'first (f.)', 'adjective'),
  v(74, 'deuxième', 'second', 'adjective'),
  v(75, 'troisième', 'third', 'adjective'),
  v(76, 'pharmacien', 'pharmacist', 'noun', 'masculine'),
  v(77, 'agent', 'agent / officer', 'noun', 'masculine'),
  v(78, 'trajet', 'route / commute', 'noun', 'masculine'),
  v(79, 'course', 'errand / race', 'noun', 'feminine'),
  v(80, 'frais', 'cool / fees', 'adjective'),
  v(81, 'visite', 'visit', 'noun', 'feminine'),
  v(82, 'visiter', 'to visit', 'verb'),
  v(83, 'recette', 'recipe / receipt', 'noun', 'feminine'),
  v(84, 'exact', 'exact / right', 'adjective'),
  v(85, 'rendez-vous', 'appointment / meeting', 'noun', 'masculine'),
  v(86, 'type', 'type / typical', 'noun', 'masculine'),
  v(87, 'ajouter', 'to add', 'verb'),
  v(88, 'fin', 'end', 'noun', 'feminine'),
  v(89, 'mars', 'March', 'noun', 'masculine'),
  v(90, 'pluriel', 'plural', 'noun', 'masculine'),
  v(91, 'alphabet', 'alphabet', 'noun', 'masculine'),
  v(92, 'cédille', 'cedilla', 'noun', 'feminine'),
  v(93, 'circonflexe', 'circumflex', 'noun', 'masculine'),
  v(94, 'orthographe', 'spelling', 'noun', 'feminine'),
  v(95, 'oral', 'spoken / oral', 'adjective'),
  v(96, 'danser', 'to dance', 'verb'),
  v(97, 'chanter', 'to sing', 'verb'),
  v(98, 'télé', 'TV', 'noun', 'feminine'),
  v(99, 'gare', 'train station', 'noun', 'feminine'),
  v(100, 'musée', 'museum', 'noun', 'masculine'),
  v(101, 'pomme', 'apple', 'noun', 'feminine'),
  v(102, 'froid', 'cold', 'adjective'),
  v(103, 'parapluie', 'umbrella', 'noun', 'masculine'),
  v(104, 'canapé', 'sofa', 'noun', 'masculine'),
  v(105, 'joli', 'pretty', 'adjective'),
  v(106, 'jolie', 'pretty (f.)', 'adjective'),
  v(107, 'bienvenue', 'welcome', 'interjection'),
  v(108, 'vert', 'green', 'adjective'),
  v(109, 'verte', 'green (f.)', 'adjective'),
  v(110, 'chaussure', 'shoe', 'noun', 'feminine'),
  v(111, 'blanc', 'white', 'adjective'),
  v(112, 'blanche', 'white (f.)', 'adjective'),
  v(113, 'soin', 'care', 'noun', 'masculine'),
  v(114, 'mettre', 'to put / to put on', 'verb'),
  v(115, 'vin', 'wine', 'noun', 'masculine'),
  v(116, 'préférer', 'to prefer', 'verb'),
  v(117, 'ë', 'ë (letter with diaeresis)', 'noun', 'masculine'),
  v(118, 'ï', 'ï (letter with diaeresis)', 'noun', 'masculine'),
  v(119, 'ü', 'ü (letter with diaeresis)', 'noun', 'masculine'),
  v(120, 'ö', 'ö (letter with diaeresis)', 'noun', 'masculine'),
  v(121, 'Alex', 'Alex (name)', 'noun', 'masculine'),
  v(122, 'Sam', 'Sam (name)', 'noun', 'masculine'),
  v(123, 'François', 'François (name)', 'noun', 'masculine'),
  v(124, 'Hélène', 'Hélène (name)', 'noun', 'feminine'),
  v(125, 'journée', 'day (period)', 'noun', 'feminine'),
  v(126, 'chronométrer', 'to time / to stopwatch', 'verb'),
  v(127, 'est-ce', 'is it (question start)', 'phrase'),
  v(128, 'est-ce que', 'do/does/is (question phrase)', 'phrase'),
  v(129, 'États-Unis', 'United States', 'noun', 'masculine'),
  v(130, "jusqu'à", 'until / up to', 'preposition'),
  v(131, 'reposer', 'to rest', 'verb'),
  v(132, 'vingt-deux', 'twenty-two', 'noun', 'masculine'),
  v(133, 'vingt-trois', 'twenty-three', 'noun', 'masculine'),
  v(134, 'vingt-cinq', 'twenty-five', 'noun', 'masculine'),
  v(135, 'vingt-et-un', 'twenty-one', 'noun', 'masculine'),
  v(136, 'déranger', 'to bother', 'verb'),
  v(137, 'conclure', 'to conclude', 'verb'),
  v(138, 'Marseille', 'Marseille', 'noun', 'feminine'),
  v(139, 'Léa', 'Léa (name)', 'noun', 'feminine'),
  v(140, 'Lea', 'Léa (name)', 'noun', 'feminine'),
  v(141, 'majuscule', 'capital letter', 'noun', 'feminine'),
  v(142, 'réponse', 'answer', 'noun', 'feminine'),
  v(143, 'date', 'date', 'noun', 'feminine'),
  v(144, 'solidement', 'solidly', 'adverb'),
  v(145, 'commencer', 'to start', 'verb'),
  v(146, 'fixer', 'to set / to fix', 'verb'),
  v(147, 'agenda', 'diary / agenda', 'noun', 'masculine'),
  v(148, 'repos', 'rest', 'noun', 'masculine'),
  v(149, 'mélanger', 'to mix', 'verb'),
  v(150, 'combiner', 'to combine', 'verb'),
  v(151, 'chiffre', 'digit / figure', 'noun', 'masculine'),
  v(152, 'comment allez-vous', 'how are you (formal)', 'phrase'),
  v(153, 'entrant', 'entering', 'adjective'),
  v(154, "d'abord", 'first / first of all', 'adverb'),
  v(155, 'ensuite', 'then / next', 'adverb'),
  v(156, 'monnaie', 'change (money)', 'noun', 'feminine'),
  v(157, 'vouvoyer', 'to use vous with someone', 'verb'),
  v(158, 'terminer', 'to finish', 'verb'),
  v(159, 'dehors', 'outside', 'adverb'),
  v(160, 'arrivant', 'arriving', 'adjective'),
  v(161, 'personnel', 'staff', 'noun', 'masculine'),
  v(162, 'toute', 'all / whole (f.)', 'adjective'),
  v(163, 'partitif', 'partitive', 'noun', 'masculine'),
  v(164, 'cliente', 'customer (f.)', 'noun', 'feminine'),
  v(165, 'posséder', 'to own', 'verb'),
  v(166, 'masculin', 'masculine', 'adjective'),
  v(167, 'féminin', 'feminine', 'adjective'),
  v(168, 'suivre', 'to follow', 'verb'),
  v(169, 'genre', 'gender / kind', 'noun', 'masculine'),
  v(170, 'possesseur', 'owner / possessor', 'noun', 'masculine'),
  v(171, 'italien', 'Italian', 'adjective'),
  v(172, 'italienne', 'Italian (f.)', 'adjective'),
  v(173, 'possessif', 'possessive', 'adjective'),
  v(174, 'appartenir', 'to belong', 'verb'),
  v(175, 'arbre', 'tree', 'noun', 'masculine'),
  v(176, 'adjectif', 'adjective', 'noun', 'masculine'),
  v(177, 'relier', 'to link', 'verb'),
  v(178, 'membre', 'member', 'noun', 'masculine'),
  v(179, 'eux', 'them / they (stressed)', 'pronoun'),
  v(180, 'ressembler', 'to resemble', 'verb'),
  v(181, 'compter', 'to count', 'verb'),
  v(182, 'tréma', 'diaeresis', 'noun', 'masculine'),
  v(183, 'Noël', 'Christmas', 'noun', 'masculine'),
  v(184, 'signe', 'sign / mark', 'noun', 'masculine'),
  v(185, 'nouveau', 'new', 'adjective'),
  v(186, 'deviner', 'to guess', 'verb'),
  v(187, 'suivant', 'following / next', 'adjective'),
  v(188, 'panneau', 'sign / panel', 'noun', 'masculine'),
  v(189, 'entendre', 'to hear', 'verb'),
  v(190, 'silencieuse', 'silent (f.)', 'adjective'),
  v(191, 'devant', 'in front of', 'preposition'),
  v(192, 'voyelle', 'vowel', 'noun', 'feminine'),
  v(193, 'épeler', 'to spell', 'verb'),
  v(194, 'sauf', 'except', 'preposition'),
  v(195, 'Dubois', 'Dubois (name)', 'noun', 'masculine'),
  v(196, 'possible', 'possible', 'adjective'),
  v(197, 'or', 'or / gold', 'conjunction'),
  v(198, 'ent', '-ent (verb ending)', 'noun', 'masculine'),
  v(199, 'courage', 'courage', 'noun', 'masculine'),
  v(200, 'mieux', 'better', 'adverb'),
  v(201, 'normal', 'normal', 'adjective'),
  v(202, 'prof', 'teacher (short)', 'noun', 'masculine'),
  v(203, 'partitives', 'partitives', 'noun', 'masculine'),
]
