import type { VocabularyWord } from '@/lib/course'

/** High-frequency learner French used in readings / fillers — keeps tap coverage high. */
function v(
  n: number,
  word: string,
  base_translation: string,
  part_of_speech: string,
  gender: 'masculine' | 'feminine' | null = null,
): VocabularyWord {
  // Namespace 4000+ — must not overlap LATER (≤841), PHASE1 (400–499), or TAP_FILL (5000+).
  const id = `10000000-0000-0000-0000-00000000${String(4000 + n).padStart(4, '0')}`
  return {
    id,
    word,
    base_translation,
    meanings: [base_translation],
    example: { french: word, english: base_translation },
    part_of_speech,
    gender,
    register: 'Courant',
    ipa_pronunciation: null,
    is_idiom: part_of_speech === 'phrase',
    is_slang: false,
    idiom_explanation: null,
  }
}

export const CORE_EXTRA_VOCABULARY: VocabularyWord[] = [
  v(5, "avant", "before", "preposition"),
  v(7, "changer", "to change", "verb"),
  v(8, "chunk", "chunk (set phrase)", "noun", 'masculine'),
  v(9, "comme", "like / as", "conjunction"),
  v(10, "complet", "complete", "adjective"),
  v(11, "complète", "complete (fem.)", "adjective"),
  v(13, "corriger", "to correct", "verb"),
  v(16, "écouter", "to listen", "verb"),
  v(17, "entier", "whole", "adjective"),
  v(18, "exemple", "example", "noun", 'masculine'),
  v(19, "forme", "form", "noun", 'feminine'),
  v(20, "formule", "set phrase", "noun", 'feminine'),
  v(21, "former", "to form", "verb"),
  v(26, "infinitif", "infinitive", "noun", 'masculine'),
  v(27, "liste", "list", "noun", 'feminine'),
  v(28, "même", "same", "adjective"),
  v(31, "petite", "small (fem.)", "adjective"),
  v(32, "phrase", "sentence", "noun", 'feminine'),
  v(33, "poser", "to ask / put", "verb"),
  v(34, "pratique", "practice", "noun", 'feminine'),
  v(35, "principal", "main", "adjective"),
  v(36, "pronom", "pronoun", "noun", 'masculine'),
  v(40, "reste", "remains", "verb"),
  v(42, "revenir", "to come back", "verb"),
  v(43, "répéter", "to repeat", "verb"),
  v(45, "sens", "meaning / sense", "noun", 'masculine'),
  v(49, "sujet", "subject", "noun", 'masculine'),
  v(52, "verbe", "verb", "noun", 'masculine'),
  v(53, "vérifier", "to check", "verb"),
  v(56, "lieu", "place", "noun", 'masculine'),
  v(58, "leçon", "lesson", "noun", 'feminine'),
  v(60, "principalement", "mainly", "adverb"),
  v(61, "sur", "on / about", "preposition"),
  v(62, "apprendre", "to learn", "verb"),
  v(63, "clair", "clear", "adjective"),
  v(64, "règle", "rule", "noun", 'feminine'),
  v(65, "sans", "without", "preposition"),
  v(66, "ne", "not (negation particle)", "adverb"),
  v(67, "pas", "not (negation)", "adverb"),
  v(68, "puis", "then", "adverb"),
  v(69, "prêt", "ready", "adjective"),
  v(70, "fini", "finished", "adjective"),
  v(71, "expliquer", "to explain", "verb"),
  v(72, "réviser", "to review / revise", "verb"),
  v(73, "travailler", "to work", "verb"),
  v(74, "montrer", "to show", "verb"),
  v(75, "produire", "to produce", "verb"),
  v(76, "falloir", "to be necessary", "verb"),
  v(77, "faut", "must / it is necessary", "verb"),
  v(78, "voix", "voice", "noun", 'feminine'),
  v(79, "haute", "high / loud (fem.)", "adjective"),
  v(80, "froide", "cold (fem.)", "adjective"),
  v(81, "vitesse", "speed", "noun", 'feminine'),
  v(82, "module", "module", "noun", 'masculine'),
  v(83, "unité", "unit", "noun", 'feminine'),
  v(84, "pronoms", "pronouns", "noun", 'masculine'),
  v(85, "passe", "passes / past (form)", "verb"),
  v(86, "parce", "because (in parce que)", "conjunction"),
  v(87, "si", "if / so", "conjunction"),
  v(88, "lui", "him / her", "pronoun"),
  v(89, "pense", "thinks", "verb"),
  v(90, "dû", "had to / owed", "verb"),
  v(91, "décidé", "decided", "adjective"),
  v(92, "fut", "was (literary past)", "verb"),
  v(93, "conformément", "in accordance with", "adverb"),
  v(94, "point", "point / at all", "noun", 'masculine'),
  v(95, "vue", "view", "noun", 'feminine'),
  v(96, "vit", "lived / saw (form)", "verb"),
  v(97, "compte", "account / counts", "noun", 'masculine'),
  v(98, "grâce", "thanks / grace", "noun", 'feminine'),
  v(99, "outre", "besides", "preposition"),
  v(100, "passé", "past", "noun", 'masculine'),
  v(101, "rendu", "rendered / returned", "adjective"),
  v(102, "faudrait", "would be necessary", "verb"),
  v(103, "checkpoint", "checkpoint", "noun", 'masculine'),
  v(104, "prove", "prove (assessment label)", "noun", 'masculine'),
  v(105, "examinateur", "examiner", "noun", 'masculine'),
  v(106, "register", "register (formality)", "noun", 'masculine'),
  v(107, "apply", "apply (grammar label)", "verb"),
  v(108, "read", "read (instruction label)", "verb"),
  v(109, "mixed", "mixed", "adjective"),
  v(110, "tense", "tense", "noun", 'masculine'),
  v(111, "pronouns", "pronouns (EN label)", "noun", 'masculine'),
  v(112, "subjunctive", "subjunctive", "noun", 'masculine'),
  v(113, "travel", "travel", "noun", 'masculine'),
  v(114, "sources", "sources", "noun", 'feminine'),
  v(115, "lens", "lens / perspective", "noun", 'masculine'),
  v(116, "chronométrez", "time yourself (imperative)", "verb"),
  v(117, "qualité", "quality", "noun", 'feminine'),
  v(118, "produisez", "produce (imperative)", "verb"),
  v(119, "montrez", "show (imperative)", "verb"),
  v(120, "maîtrisez", "master (imperative)", "verb"),
  v(121, "indices", "hints", "noun", 'masculine'),
  v(122, "épreuve", "test / assessment", "noun", 'feminine'),
  v(123, "futur", "future", "noun", 'masculine'),
  v(124, "cause", "cause", "noun", 'feminine'),
  v(125, "prier", "to pray / ask", "verb"),
  v(126, "proche", "close / nearby", "adjective"),
  v(127, "pièce", "piece / room", "noun", 'feminine'),
  v(128, "mangé", "eaten", "adjective"),
  v(129, "me", "me", "pronoun"),
  v(130, "te", "you (object)", "pronoun"),
  v(131, "devoir", "to have to / must", "verb"),
  v(132, "dois", "must / owe (form)", "verb"),
  v(133, "vocab", "vocab (short)", "noun", 'masculine'),
  v(138, "vs", "versus", "preposition"),
  v(139, "PC", "PC (passé composé label)", "noun", 'masculine'),
  v(140, "PS", "PS (passé simple label)", "noun", 'masculine'),
  v(141, "parla", "spoke (literary past)", "verb"),
  v(143, "émotions", "emotions", "noun", 'feminine'),
  v(144, "irregular", "irregular (grammar label)", "adjective"),
  v(145, "past", "past (grammar label)", "adjective"),
  v(146, "full", "full (grammar label)", "adjective"),
  v(147, "paragraph", "paragraph", "noun", 'masculine'),
  v(148, "recognition", "recognition", "noun", 'feminine'),
  v(149, "intro", "intro", "noun", 'feminine'),
  v(150, "outil", "tool", "noun", 'masculine'),
  v(151, "séparé", "separate / separated", "adjective"),
  v(152, "séparer", "to separate", "verb"),
  v(156, "tard", "late", "adverb"),
  v(157, "tôt", "early", "adverb"),
  v(158, "pleuvoir", "to rain", "verb"),
  v(159, "pleut", "it rains / is raining", "verb"),
  v(160, "pleuvait", "it was raining", "verb"),
  v(161, "lever", "to raise / get up", "verb"),
  v(162, "gauche", "left", "noun", 'feminine'),
  v(163, "droite", "right", "noun", 'feminine'),
  v(164, "calme", "calm", "adjective"),
  v(165, "emploi", "job", "noun", 'masculine'),
  v(166, "temps", "time / weather", "noun", 'masculine'),
  v(167, "intéressant", "interesting", "adjective"),
  v(168, "demie", "half (fem.)", "noun", 'feminine'),
  v(169, "mal", "badly / pain", "adverb"),
  v(170, "double", "double", "adjective"),
  v(172, "devenue", "become (fem. past)", "verb"),
  v(173, "fruit", "fruit", "noun", 'masculine'),
  v(174, "neige", "snow", "noun", 'feminine'),
  v(175, "content", "happy / glad", "adjective"),
  v(176, "composé", "composed / compound", "adjective"),
  v(177, "promettre", "to promise", "verb"),
  v(178, "promets", "promise (form)", "verb"),
  v(179, "correct", "correct", "adjective"),
  v(180, "quart", "quarter", "noun", 'masculine'),
  v(181, "peur", "fear", "noun", 'feminine'),
  v(182, "près", "near", "adverb"),
  v(183, "postal", "postal", "adjective"),
  v(184, "réussir", "to succeed", "verb"),
  v(185, "réussi", "succeeded", "adjective"),
  v(186, "accent", "accent", "noun", 'masculine'),
  v(187, "monsieur", "sir / mister", "noun", 'masculine'),
  v(188, "laver", "to wash", "verb"),
  v(189, "lire", "to read", "verb"),
  v(190, "sport", "sport", "noun", 'masculine'),
  v(191, "journée", "day (duration)", "noun", 'feminine'),
  v(192, "salle", "room / hall", "noun", 'feminine'),
  v(193, "bain", "bath", "noun", 'masculine'),
  v(194, "stylo", "pen", "noun", 'masculine'),
  v(195, "printemps", "spring", "noun", 'masculine'),
  v(196, "hiver", "winter", "noun", 'masculine'),
  v(197, "robe", "dress", "noun", 'feminine'),
  v(198, "pull", "sweater", "noun", 'masculine'),
  v(199, "corps", "body", "noun", 'masculine'),
  v(200, "livre", "book", "noun", 'masculine'),
  v(201, "marché", "market / walked", "noun", 'masculine'),
  v(202, "marcher", "to walk", "verb"),
  v(203, "penser", "to think", "verb"),
  v(204, "téléphone", "phone", "noun", 'masculine'),
]
