import type { VocabularyWord } from '@/lib/course'

/** High-frequency learner French used in readings / fillers — keeps tap coverage high. */
function v(
  n: number,
  word: string,
  base_translation: string,
  part_of_speech: string,
  gender: 'masculine' | 'feminine' | null = null,
): VocabularyWord {
  const id = `10000000-0000-0000-0000-00000000${String(800 + n).padStart(4, '0')}`
  return {
    id,
    word,
    base_translation,
    meanings: [base_translation],
    example: { french: word, english: base_translation },
    part_of_speech,
    gender,
    register: 'Courant',
    ipa_pronunciation: null,
    is_idiom: part_of_speech === 'phrase',
    is_slang: false,
    idiom_explanation: null,
  }
}

export const CORE_EXTRA_VOCABULARY: VocabularyWord[] = [
  v(1, 'accord', 'agreement', 'noun', 'masculine'),
  v(2, 'ami', 'friend', 'noun', 'masculine'),
  v(3, 'article', 'article', 'noun', 'masculine'),
  v(4, 'aussi', 'also', 'adverb'),
  v(5, 'avant', 'before', 'preposition'),
  v(6, 'bien', 'well', 'adverb'),
  v(7, 'changer', 'to change', 'verb'),
  v(8, 'chunk', 'chunk (set phrase)', 'noun', 'masculine'),
  v(9, 'comme', 'like / as', 'conjunction'),
  v(10, 'complet', 'complete', 'adjective'),
  v(11, 'complète', 'complete (fem.)', 'adjective'),
  v(12, 'comprendre', 'to understand', 'verb'),
  v(13, 'corriger', 'to correct', 'verb'),
  v(14, 'dans', 'in', 'preposition'),
  v(15, 'donner', 'to give', 'verb'),
  v(16, 'écouter', 'to listen', 'verb'),
  v(17, 'entier', 'whole', 'adjective'),
  v(18, 'exemple', 'example', 'noun', 'masculine'),
  v(19, 'forme', 'form', 'noun', 'feminine'),
  v(20, 'formule', 'set phrase', 'noun', 'feminine'),
  v(21, 'former', 'to form', 'verb'),
  v(22, 'français', 'French', 'adjective'),
  v(23, 'idée', 'idea', 'noun', 'feminine'),
  v(24, 'important', 'important', 'adjective'),
  v(25, 'inconnu', 'stranger / unknown', 'noun', 'masculine'),
  v(26, 'infinitif', 'infinitive', 'noun', 'masculine'),
  v(27, 'liste', 'list', 'noun', 'feminine'),
  v(28, 'même', 'same', 'adjective'),
  v(29, 'mot', 'word', 'noun', 'masculine'),
  v(30, 'parler', 'to speak', 'verb'),
  v(31, 'petite', 'small (fem.)', 'adjective'),
  v(32, 'phrase', 'sentence', 'noun', 'feminine'),
  v(33, 'poser', 'to ask / put', 'verb'),
  v(34, 'pratique', 'practice', 'noun', 'feminine'),
  v(35, 'principal', 'main', 'adjective'),
  v(36, 'pronom', 'pronoun', 'noun', 'masculine'),
  v(37, 'question', 'question', 'noun', 'feminine'),
  v(38, 'registre', 'register (formality)', 'noun', 'masculine'),
  v(39, 'répondre', 'to answer', 'verb'),
  v(40, 'reste', 'remains', 'verb'),
  v(41, 'rester', 'to stay / remain', 'verb'),
  v(42, 'revenir', 'to come back', 'verb'),
  v(43, 'répéter', 'to repeat', 'verb'),
  v(44, 'scène', 'scene', 'noun', 'feminine'),
  v(45, 'sens', 'meaning / sense', 'noun', 'masculine'),
  v(46, 'simple', 'simple', 'adjective'),
  v(47, 'souvent', 'often', 'adverb'),
  v(48, 'structure', 'structure', 'noun', 'feminine'),
  v(49, 'sujet', 'subject', 'noun', 'masculine'),
  v(50, 'utiliser', 'to use', 'verb'),
  v(51, 'utile', 'useful', 'adjective'),
  v(52, 'verbe', 'verb', 'noun', 'masculine'),
  v(53, 'vérifier', 'to check', 'verb'),
  v(54, 'vocabulaire', 'vocabulary', 'noun', 'masculine'),
  v(55, 'voici', 'here is/are', 'adverb'),
  v(56, 'lieu', 'place', 'noun', 'masculine'),
  v(57, 'où', 'where', 'adverb'),
  v(58, 'leçon', 'lesson', 'noun', 'feminine'),
  v(59, 'aujourd\'hui', 'today', 'adverb'),
  v(60, 'principalement', 'mainly', 'adverb'),
]
